/* Generated by Nim Compiler v0.17.1 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/p/Nim/lib -o /p/calendars/test/nimcache/calendars_tests.o /p/calendars/test/nimcache/calendars_tests.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ;
typedef struct ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct TestResult_GEvSVSxdPWWgMGM48ywEYQ TestResult_GEvSVSxdPWWgMGM48ywEYQ;
typedef struct RootObj RootObj;
typedef struct StreamObj_RShkcoDOPnoCVhtpN1hDPQ StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw {
  RootObj Sup;
};
struct JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ {
  OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream;
TY_sM4lkSb7zS6F7OVMvW9cffQ* testErrors;
NF testStartTime;
NimStringDesc* testStackTrace;
};
typedef NU8 OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww;
struct ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw {
  OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
NIM_BOOL colorOutput;
OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel;
NIM_BOOL isInSuite;
NIM_BOOL isInTest;
};
typedef NU8 TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ;
struct TestResult_GEvSVSxdPWWgMGM48ywEYQ {
NimStringDesc* suiteName;
NimStringDesc* testName;
TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ status;
};
typedef N_NIMCALL_PTR(void, TY_cnkJEp9bna8U6yi9aVW9cAJ0Q) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY_KjFcmLOhf4VQvVcyLJWXZw) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, TY_jlOYFw9cHausuCbPoWx2iiA) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY_Xzm85qBLb9cf9cu8VOfAr8PQ) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, TY_tjaJtoUzLe1BMUbItlcGhQ) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, TY_b9bsIuILxTLVZHPvJBW187A) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
TY_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
TY_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
TY_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
TY_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
TY_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
TY_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, chckNilDisp)(void* p);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NOINLINE(NIM_BOOL, isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NIMCALL(void, suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* suiteName);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(void, suiteStarted_IXWI0IZVUaexE074PboPzQ)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* suiteName);
N_NIMCALL(void, suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, testStarted_EYS8dFM0pZmDNdV9c1cyo4Q)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* testName);
N_NIMCALL(void, testStarted_0WlfvTsMUPRHUfLeuXrGAg)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* testName);
N_NIMCALL(void, testStarted_YRuPwQXlDxZko9bSMypk3hA)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName);
N_NIMCALL(void, failureOccurred_NAlHeCfOfz1bBvtw2rCPGw)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(void, failureOccurred_HopmjhtOQil8N9axQ5kNI3w)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(void, failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(void, testEnded_E5f9a05hVCAPvYslPV2f4TQ)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(void, testEnded_AsoOYSa1sGgPTBsUoT9cxsw)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(void, testEnded_hPRwDS9aOIRJ5MB9buAX30Wg)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(void, suiteEnded_EF53BADEiH9a6amiy7eitMg_2)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter);
N_NIMCALL(void, suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter);
N_NIMCALL(void, suiteEnded_RS3dEHKAbuhOugXu1dXVHg)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unittestInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unittestDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_calendarsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_calendarsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_test_calendarsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_test_calendarsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_timestampsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_timestampsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_test_timestampsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_test_timestampsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_timezonesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_timezonesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_test_timezonesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, calendars_test_timezonesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, testsDatInit000)(void);
extern TNimType NTI_kvLOVRX6Za2S0C2QxHXy9cQ_;
static TNimType* Nim_OfCheck_CACHE3[2];
extern TNimType NTI_dU6QGtP3KgqXg9bZP3nhpWw_;
static TNimType* Nim_OfCheck_CACHE4[2];
extern TNimType NTI_dLGU9cWWYqlqOn8lpRVsx9cw_;
static TNimType* Nim_OfCheck_CACHE5[2];
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
static TNimType* Nim_OfCheck_CACHE6[2];
static TNimType* Nim_OfCheck_CACHE7[2];
static TNimType* Nim_OfCheck_CACHE8[2];
static TNimType* Nim_OfCheck_CACHE9[2];
static TNimType* Nim_OfCheck_CACHE10[2];
static TNimType* Nim_OfCheck_CACHE11[2];
static TNimType* Nim_OfCheck_CACHE12[2];
static TNimType* Nim_OfCheck_CACHE13[2];
static TNimType* Nim_OfCheck_CACHE14[2];
static TNimType* Nim_OfCheck_CACHE15[2];
static TNimType* Nim_OfCheck_CACHE16[2];
static TNimType* Nim_OfCheck_CACHE17[2];

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!(obj == subclass)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!((*obj).base == subclass)) goto LA7_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA7_: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA11_: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA15_: ;
	result = isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg(obj, subclass, cache);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, suiteStarted_GgW0QiD89cMFXShyPQ8t8qg)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName) {
	nimfr_("suiteStarted", "unittest.nim")
	nimln_(118, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE3)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw(((JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), suiteName);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE4)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		suiteStarted_IXWI0IZVUaexE074PboPzQ(((ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), suiteName);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE5)))) goto LA9_;
		suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA(formatter, suiteName);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_NIMCALL(void, testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "unittest.nim")
	nimln_(120, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE6)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		testStarted_EYS8dFM0pZmDNdV9c1cyo4Q(((JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), testName);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE7)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		testStarted_0WlfvTsMUPRHUfLeuXrGAg(((ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), testName);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE8)))) goto LA9_;
		testStarted_YRuPwQXlDxZko9bSMypk3hA(formatter, testName);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_NIMCALL(void, failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	nimfr_("failureOccurred", "unittest.nim")
	nimln_(122, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE9)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		failureOccurred_NAlHeCfOfz1bBvtw2rCPGw(((JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), checkpoints, stackTrace);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE10)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		failureOccurred_HopmjhtOQil8N9axQ5kNI3w(((ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), checkpoints, stackTrace);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE11)))) goto LA9_;
		failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw(formatter, checkpoints, stackTrace);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_NIMCALL(void, testEnded_azSnnJ3hAiHHuUdLzViJlw)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult) {
	nimfr_("testEnded", "unittest.nim")
	nimln_(126, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE12)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		testEnded_E5f9a05hVCAPvYslPV2f4TQ(((JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), testResult);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE13)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		testEnded_AsoOYSa1sGgPTBsUoT9cxsw(((ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), testResult);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE14)))) goto LA9_;
		testEnded_hPRwDS9aOIRJ5MB9buAX30Wg(formatter, testResult);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_NIMCALL(void, suiteEnded_K2O75e2roACICAuYiNImyw)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter) {
	nimfr_("suiteEnded", "unittest.nim")
	nimln_(128, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE15)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		suiteEnded_EF53BADEiH9a6amiy7eitMg_2(((JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)));
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE16)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA(((ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)));
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE17)))) goto LA9_;
		suiteEnded_RS3dEHKAbuhOugXu1dXVHg(formatter);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_termiosDatInit000();
	stdlib_terminalDatInit000();
	stdlib_unittestDatInit000();
	calendars_calendarsDatInit000();
	calendars_test_calendarsDatInit000();
	calendars_timestampsDatInit000();
	calendars_test_timestampsDatInit000();
	stdlib_lexbaseDatInit000();
	stdlib_parsecsvDatInit000();
	calendars_timezonesDatInit000();
	calendars_test_timezonesDatInit000();
	testsDatInit000();
	stdlib_macrosInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_streamsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_termiosInit000();
	stdlib_terminalInit000();
	stdlib_unittestInit000();
	calendars_calendarsInit000();
	calendars_test_calendarsInit000();
	calendars_timestampsInit000();
	calendars_test_timestampsInit000();
	stdlib_lexbaseInit000();
	stdlib_parsecsvInit000();
	calendars_timezonesInit000();
	calendars_test_timezonesInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("tests", "tests.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, testsDatInit000)(void) {
}

