/* Generated by Nim Compiler v0.17.1 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/p/Nim/lib -o /p/calendars/test/nimcache/stdlib_unittest.o /p/calendars/test/nimcache/stdlib_unittest.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY_2gM6knqz8MaAY9c4MAR2ztg TY_2gM6knqz8MaAY9c4MAR2ztg;
typedef struct OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw;
typedef struct RootObj RootObj;
typedef struct TestResult_GEvSVSxdPWWgMGM48ywEYQ TestResult_GEvSVSxdPWWgMGM48ywEYQ;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw;
typedef struct JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ;
typedef struct StreamObj_RShkcoDOPnoCVhtpN1hDPQ StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct RootObj {
TNimType* m_type;
};
struct OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw {
  RootObj Sup;
};
struct Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct IntSet_EZObFrE3NC9bIb3YMkY9crZA {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef NU8 OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww;
struct ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw {
  OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
NIM_BOOL colorOutput;
OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel;
NIM_BOOL isInSuite;
NIM_BOOL isInTest;
};
typedef NU8 Style_NXKayqTLMsAibFwNceBlpA_Set;
typedef NU8 ForegroundColor_ez9ah4IgQc0AbdW68acioDg;
typedef NU8 TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ;
struct TestResult_GEvSVSxdPWWgMGM48ywEYQ {
NimStringDesc* suiteName;
NimStringDesc* testName;
TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ status;
};
struct JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ {
  OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream;
TY_sM4lkSb7zS6F7OVMvW9cffQ* testErrors;
NF testStartTime;
NimStringDesc* testStackTrace;
};
typedef NimStringDesc* TY_nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ;
typedef NimStringDesc* TY_Re75IspeoxXy2oCZHwcRrA[2];
struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct PageDesc_fublkgIY4LG3mT51LU2WHg {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef N_NIMCALL_PTR(void, TY_cnkJEp9bna8U6yi9aVW9cAJ0Q) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY_KjFcmLOhf4VQvVcyLJWXZw) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, TY_jlOYFw9cHausuCbPoWx2iiA) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY_Xzm85qBLb9cf9cu8VOfAr8PQ) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, TY_tjaJtoUzLe1BMUbItlcGhQ) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, TY_b9bsIuILxTLVZHPvJBW187A) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
TY_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
TY_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
TY_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
TY_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
TY_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
TY_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY_2gM6knqz8MaAY9c4MAR2ztg {
  TGenericSeq Sup;
  OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(TY_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, Marker_TY_po6hYFavJCZm28qf1dR3mw)(void* p, NI op);
static N_NIMCALL(void, Marker_TY_2gM6knqz8MaAY9c4MAR2ztg)(void* p, NI op);
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_3)(void);
N_NIMCALL(NIM_BOOL, existsEnv_ahpnHkfRE9cLlJNaRpEL7Vw)(NimStringDesc* key);
N_NIMCALL(void, suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, testStarted_YRuPwQXlDxZko9bSMypk3hA)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName);
N_NIMCALL(void, failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(void, testEnded_hPRwDS9aOIRJ5MB9buAX30Wg)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(void, suiteEnded_RS3dEHKAbuhOugXu1dXVHg)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter);
N_NIMCALL(NIM_BOOL, eqeq__z9cxc4k8iqgnw41zdA8grdw)(TY_2gM6knqz8MaAY9c4MAR2ztg* x, TY_2gM6knqz8MaAY9c4MAR2ztg* y);
N_NIMCALL(void, addOutputFormatter_4nkd7g9ax9bLTtQYMNO9cp0Ag)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter);
N_NIMCALL(void, nimGCunref)(void* p);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*, newConsoleOutputFormatter_Qc9aWnvhC1i9b49a9aCcLwN9cWw)(OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel, NIM_BOOL colorOutput);
static N_NIMCALL(void, Marker_TY_ExFEz8ninaqkX3e4eolu7g)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*, defaultConsoleFormatter_5cci6OIDr79cInvvSsLn6vg)(void);
N_NIMCALL(NimStringDesc*, getEnv_8zNgT9bxx7m9cTt2TeVdTdIw)(NimStringDesc* key);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, suiteStarted_IXWI0IZVUaexE074PboPzQ)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* suiteName);
N_NIMCALL(void, setStyle_zEKKPPIjKZs9bVYu4TwenLg)(FILE* f, Style_NXKayqTLMsAibFwNceBlpA_Set style);
N_NIMCALL(void, setForegroundColor_Tw7yxMupneOmAicqiYt3NA)(FILE* f, ForegroundColor_ez9ah4IgQc0AbdW68acioDg fg, NIM_BOOL bright);
N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_NIMCALL(void, resetAttributes_tFIu39aFSR3N0M64Ynwugng_5)(FILE* f);
N_NIMCALL(void, testStarted_0WlfvTsMUPRHUfLeuXrGAg)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* testName);
N_NIMCALL(void, failureOccurred_HopmjhtOQil8N9axQ5kNI3w)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(void, testEnded_AsoOYSa1sGgPTBsUoT9cxsw)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(void, suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter);
N_NIMCALL(NimStringDesc*, xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*, newJUnitOutputFormatter_PqqpGJPZVHC1k3JX9cfStQQ)(StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream);
static N_NIMCALL(void, Marker_TY_OU9b9b9b3svfAf0YBTEFQsJag)(void* p, NI op);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_NIMCALL(void, writeLine_G1TKFmud9akiH9bzSHWMshag_2)(StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NimStringDesc** args, NI argsLen_0);
N_NIMCALL(void, close_EF53BADEiH9a6amiy7eitMg)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter);
N_NIMCALL(void, close_4ed7IXme7lqtClFI7s2sTQ_2)(StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
N_NIMCALL(void, suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* suiteName);
N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(void, testStarted_EYS8dFM0pZmDNdV9c1cyo4Q)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* testName);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(void, add_sp11IzYl5roq19bn4qRQmqA)(TY_sM4lkSb7zS6F7OVMvW9cffQ** x, NimStringDesc** y, NI yLen_0);
N_NIMCALL(void, failureOccurred_NAlHeCfOfz1bBvtw2rCPGw)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(void, testEnded_E5f9a05hVCAPvYslPV2f4TQ)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f, FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ format, NI precision, NIM_CHAR decimalSep);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, suiteEnded_EF53BADEiH9a6amiy7eitMg_2)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter);
N_NIMCALL(NIM_BOOL, shouldRun_ONH9bpFQB7Lkusu9bdW9bZB9bg)(NimStringDesc* testName);
N_NIMCALL(void, ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg)(void);
N_NIMCALL(void, suiteEnded_8zybqvexf9aYkm9bmgyU3eLg_2)(void);
N_NIMCALL(void, suiteEnded_K2O75e2roACICAuYiNImyw)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter);
N_NIMCALL(void, testEnded_xoIS1BdhYWQ6hhMP22XXiw)(TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(void, testEnded_azSnnJ3hAiHHuUdLzViJlw)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(NIM_BOOL, eqeq__SRlIwYUUH1G46Yee9aMIFAQ)(TY_sM4lkSb7zS6F7OVMvW9cffQ* x, TY_sM4lkSb7zS6F7OVMvW9cffQ* y);
N_NIMCALL(void, checkpoint_4nBz3prx9cKVVOoTZb4rNCQ)(NimStringDesc* msg);
static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwunittest)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQunittest)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
NIM_BOOL abortOnError_Bte3Uiwc4Q19ago2N4C89cUA;
TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
TY_2gM6knqz8MaAY9c4MAR2ztg* formatters_55U7g4zhjHV9bCI6emTgDiA;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_dLGU9cWWYqlqOn8lpRVsx9cw_;
TNimType NTI_po6hYFavJCZm28qf1dR3mw_;
TNimType NTI_2gM6knqz8MaAY9c4MAR2ztg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_dU6QGtP3KgqXg9bZP3nhpWw_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_7UfTrIPsm9cGDPwH9bpwJDww_;
TNimType NTI_ExFEz8ninaqkX3e4eolu7g_;
TNimType NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_;
TNimType NTI_kvLOVRX6Za2S0C2QxHXy9cQ_;
extern TNimType NTI_r3Wc5tOoxP8rz1DvGVTUvw_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_OU9b9b9b3svfAf0YBTEFQsJag_;
TNimType NTI_GEvSVSxdPWWgMGM48ywEYQ_;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_4, "NIMTEST_ABORT_ON_ERROR", 22);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_9, "NIMTEST_OUTPUT_LVL", 18);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_10, "NIMTEST_NO_COLOR", 16);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_12, "\012[Suite] ", 9);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_13, "\012", 1);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_14, "    ", 4);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_15, "", 0);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_17, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_18, "  ", 2);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_19, "[", 1);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_23, "] ", 2);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_24, "&lt;", 4);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_25, "&gt;", 4);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_26, "&amp;", 5);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_27, "&quot;", 6);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_28, "&apos;", 6);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_29, "&#", 2);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_31, "len(a) == L string modified while iterating over it", 51);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_34, "<\?xml version=\"1.0\" encoding=\"UTF-8\"\?>", 38);
NIM_CONST TY_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_33 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_34)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_36, "<testsuites>", 12);
NIM_CONST TY_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_35 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_36)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_38, "</testsuites>", 13);
NIM_CONST TY_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_37 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_38)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_39, "\011<testsuite name=\"$1\">", 22);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_40, "\011\011<testcase name=\"$#\" time=\"$#\">", 32);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_42, "<skipped />", 11);
NIM_CONST TY_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_41 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_42)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_44, "The test failed without outputting an error", 43);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_48, "\011\011\011<error message=\"$#\">$#</error>", 33);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_49, "\011\011\011<system-err>$#</system-err>", 30);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_50, "\011\011\011<failure message=\"$#\">$#</failure>", 37);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_52, "\011\011</testcase>", 13);
NIM_CONST TY_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_51 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_52)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_54, "\011</testsuite>", 13);
NIM_CONST TY_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_53 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_54)}
;
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_2)(void) {
	nimGCvisit((void*)checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, 0);
}
static N_NIMCALL(void, Marker_TY_po6hYFavJCZm28qf1dR3mw)(void* p, NI op) {
	OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* a;
	a = (OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*)p;
}
static N_NIMCALL(void, Marker_TY_2gM6knqz8MaAY9c4MAR2ztg)(void* p, NI op) {
	TY_2gM6knqz8MaAY9c4MAR2ztg* a;
	NI T1_;
	a = (TY_2gM6knqz8MaAY9c4MAR2ztg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_3)(void) {
	nimGCvisit((void*)formatters_55U7g4zhjHV9bCI6emTgDiA, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName) {
	nimfr_("suiteStarted", "unittest.nim")
	popFrame();
}

N_NIMCALL(void, testStarted_YRuPwQXlDxZko9bSMypk3hA)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "unittest.nim")
	popFrame();
}

N_NIMCALL(void, failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	nimfr_("failureOccurred", "unittest.nim")
	popFrame();
}

N_NIMCALL(void, testEnded_hPRwDS9aOIRJ5MB9buAX30Wg)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult) {
	nimfr_("testEnded", "unittest.nim")
	popFrame();
}

N_NIMCALL(void, suiteEnded_RS3dEHKAbuhOugXu1dXVHg)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter) {
	nimfr_("suiteEnded", "unittest.nim")
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim")
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim")
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim")
	nimln_(266, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(364, "system.nim");
		nimln_(266, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(267, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(364, "system.nim");
		nimln_(267, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(268, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, addOutputFormatter_4nkd7g9ax9bLTtQYMNO9cp0Ag)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter) {
	nimfr_("addOutputFormatter", "unittest.nim")
	nimln_(132, "unittest.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq__z9cxc4k8iqgnw41zdA8grdw(formatters_55U7g4zhjHV9bCI6emTgDiA, NIM_NIL);
		if (!T3_) goto LA4_;
		nimln_(133, "unittest.nim");
		if (formatters_55U7g4zhjHV9bCI6emTgDiA) nimGCunref(formatters_55U7g4zhjHV9bCI6emTgDiA);
		formatters_55U7g4zhjHV9bCI6emTgDiA = (TY_2gM6knqz8MaAY9c4MAR2ztg*) newSeqRC1((&NTI_2gM6knqz8MaAY9c4MAR2ztg_), 1);
		asgnRef((void**) (&formatters_55U7g4zhjHV9bCI6emTgDiA->data[0]), formatter);
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(135, "unittest.nim");
		formatters_55U7g4zhjHV9bCI6emTgDiA = (TY_2gM6knqz8MaAY9c4MAR2ztg*) incrSeqV2(&(formatters_55U7g4zhjHV9bCI6emTgDiA)->Sup, sizeof(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*));
		asgnRef((void**) (&formatters_55U7g4zhjHV9bCI6emTgDiA->data[formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len]), formatter);
		++formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len;
	}
	LA1_: ;
	popFrame();
}
static N_NIMCALL(void, Marker_TY_ExFEz8ninaqkX3e4eolu7g)(void* p, NI op) {
	ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* a;
	a = (ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*)p;
}

N_NIMCALL(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*, newConsoleOutputFormatter_Qc9aWnvhC1i9b49a9aCcLwN9cWw)(OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel, NIM_BOOL colorOutput) {
	ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* result;
	ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* T1_;
	nimfr_("newConsoleOutputFormatter", "unittest.nim")
	result = (ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*)0;
	nimln_(139, "unittest.nim");
	T1_ = (ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*)0;
	T1_ = (ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) newObj((&NTI_ExFEz8ninaqkX3e4eolu7g_), sizeof(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw));
	(*T1_).Sup.Sup.m_type = (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_);
	(*T1_).outputLevel = outputLevel;
	(*T1_).colorOutput = colorOutput;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*, defaultConsoleFormatter_5cci6OIDr79cInvvSsLn6vg)(void) {
	ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* result;
	NimStringDesc* envOutLvl;
	NIM_BOOL colorOutput;
	NIM_BOOL T1_;
	OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel;
	nimfr_("defaultConsoleFormatter", "unittest.nim")
	result = (ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*)0;
	nimln_(148, "unittest.nim");
	envOutLvl = getEnv_8zNgT9bxx7m9cTt2TeVdTdIw(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_9));
	nimln_(149, "unittest.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = existsEnv_ahpnHkfRE9cLlJNaRpEL7Vw(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_10));
	colorOutput = !(T1_);
	nimln_(150, "unittest.nim");
	outputLevel = ((OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 0);
	nimln_(151, "unittest.nim");
	{
		if (!(((NI) 0) < (envOutLvl ? envOutLvl->Sup.len : 0))) goto LA4_;
		{
			OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww opt;
			NI res;
			opt = (OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww)0;
			nimln_(1961, "system.nim");
			res = ((NI) 0);
			{
				nimln_(1962, "system.nim");
				while (1) {
					NI TM_Um3CQPZ9bILAIolZOsxNIaw_11;
					if (!(res <= ((NI) 2))) goto LA8;
					nimln_(1963, "system.nim");
					opt = ((OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww)chckRange(res, ((OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 0), ((OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 2)));
					nimln_(153, "unittest.nim");
					{
						if (!eqStrings(reprEnum((NI)opt, (&NTI_7UfTrIPsm9cGDPwH9bpwJDww_)), envOutLvl)) goto LA11_;
						nimln_(154, "unittest.nim");
						outputLevel = opt;
						nimln_(155, "unittest.nim");
						goto LA6;
					}
					LA11_: ;
					nimln_(1964, "system.nim");
					TM_Um3CQPZ9bILAIolZOsxNIaw_11 = addInt(res, ((NI) 1));
					res = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_11);
				} LA8: ;
			}
		} LA6: ;
	}
	LA4_: ;
	nimln_(156, "unittest.nim");
	result = newConsoleOutputFormatter_Qc9aWnvhC1i9b49a9aCcLwN9cWw(outputLevel, colorOutput);
	popFrame();
	return result;
}

N_NIMCALL(void, suiteStarted_IXWI0IZVUaexE074PboPzQ)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* suiteName) {
	nimfr_("suiteStarted", "unittest.nim")
	nimln_(163, "unittest.nim");
	{
		if (!(*formatter).colorOutput) goto LA3_;
		nimln_(620, "terminal.nim");
		setStyle_zEKKPPIjKZs9bVYu4TwenLg(stdout, 1);
		setForegroundColor_Tw7yxMupneOmAicqiYt3NA(stdout, ((ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 34), NIM_FALSE);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_12));
		resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, suiteName);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_13));
		resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(161, "unittest.nim");
		printf("%s%s\012", ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_12)? (((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_12))->data:"nil", suiteName? (suiteName)->data:"nil");
		fflush(stdout);
	}
	LA1_: ;
	nimln_(167, "unittest.nim");
	(*formatter).isInSuite = NIM_TRUE;
	popFrame();
}

N_NIMCALL(void, testStarted_0WlfvTsMUPRHUfLeuXrGAg)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "unittest.nim")
	nimln_(170, "unittest.nim");
	(*formatter).isInTest = NIM_TRUE;
	popFrame();
}

N_NIMCALL(void, failureOccurred_HopmjhtOQil8N9axQ5kNI3w)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	NimStringDesc* prefix;
	nimfr_("failureOccurred", "unittest.nim")
	nimln_(173, "unittest.nim");
	{
		nimln_(364, "system.nim");
		nimln_(173, "unittest.nim");
		if (!!((stackTrace == NIM_NIL))) goto LA3_;
		nimln_(174, "unittest.nim");
		printf("%s\012", stackTrace? (stackTrace)->data:"nil");
		fflush(stdout);
	}
	LA3_: ;
	nimln_(175, "unittest.nim");
	{
		if (!(*formatter).isInSuite) goto LA7_;
		prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_14));
	}
	goto LA5_;
	LA7_: ;
	{
		prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_15));
	}
	LA5_: ;
	{
		NimStringDesc* msg;
		NI i;
		NI L;
		msg = (NimStringDesc*)0;
		nimln_(3626, "system.nim");
		i = ((NI) 0);
		nimln_(3627, "system.nim");
		L = (checkpoints ? checkpoints->Sup.len : 0);
		{
			nimln_(3628, "system.nim");
			while (1) {
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_16;
				if (!(i < L)) goto LA12;
				nimln_(3629, "system.nim");
				if ((NU)(i) >= (NU)(checkpoints->Sup.len)) raiseIndexError();
				msg = checkpoints->data[i];
				nimln_(177, "unittest.nim");
				printf("%s%s\012", prefix? (prefix)->data:"nil", msg? (msg)->data:"nil");
				fflush(stdout);
				nimln_(3630, "system.nim");
				TM_Um3CQPZ9bILAIolZOsxNIaw_16 = addInt(i, ((NI) 1));
				i = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_16);
				nimln_(3631, "system.nim");
				{
					if (!!(((checkpoints ? checkpoints->Sup.len : 0) == L))) goto LA15_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_17));
				}
				LA15_: ;
			} LA12: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, testEnded_AsoOYSa1sGgPTBsUoT9cxsw)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult) {
	nimfr_("testEnded", "unittest.nim")
	nimln_(180, "unittest.nim");
	(*formatter).isInTest = NIM_FALSE;
	nimln_(182, "unittest.nim");
	{
		NIM_BOOL T3_;
		NIM_BOOL T5_;
		NimStringDesc* prefix;
		T3_ = (NIM_BOOL)0;
		nimln_(364, "system.nim");
		nimln_(182, "unittest.nim");
		T3_ = !(((*formatter).outputLevel == ((OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 2)));
		if (!(T3_)) goto LA4_;
		nimln_(183, "unittest.nim");
		T5_ = (NIM_BOOL)0;
		T5_ = ((*formatter).outputLevel == ((OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 0));
		if (T5_) goto LA6_;
		T5_ = ((*testResult).status == ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1));
		LA6_: ;
		T3_ = T5_;
		LA4_: ;
		if (!T3_) goto LA7_;
		nimln_(184, "unittest.nim");
		{
			nimln_(364, "system.nim");
			nimln_(184, "unittest.nim");
			if (!!(((*testResult).suiteName == NIM_NIL))) goto LA11_;
			prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_18));
		}
		goto LA9_;
		LA11_: ;
		{
			prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_15));
		}
		LA9_: ;
		nimln_(187, "unittest.nim");
		{
			NIM_BOOL T16_;
			ForegroundColor_ez9ah4IgQc0AbdW68acioDg color;
			T16_ = (NIM_BOOL)0;
			T16_ = (*formatter).colorOutput;
			if (!(T16_)) goto LA17_;
			T16_ = NIM_TRUE;
			LA17_: ;
			if (!T16_) goto LA18_;
			nimln_(188, "unittest.nim");
			switch ((*testResult).status) {
			case ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0):
			{
				color = ((ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 32);
			}
			break;
			case ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1):
			{
				color = ((ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 31);
			}
			break;
			case ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 2):
			{
				color = ((ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 33);
			}
			break;
			default:
			{
				color = ((ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 37);
			}
			break;
			}
			nimln_(620, "terminal.nim");
			setStyle_zEKKPPIjKZs9bVYu4TwenLg(stdout, 1);
			setForegroundColor_Tw7yxMupneOmAicqiYt3NA(stdout, color, NIM_FALSE);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, prefix);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_19));
			nimln_(193, "unittest.nim");
			write_c4mGyJBvK73pdM22jiweKQ(stdout, reprEnum((NI)(*testResult).status, (&NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_)));
			nimln_(620, "terminal.nim");
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_23));
			resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, (*testResult).testName);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_13));
			resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
		}
		goto LA14_;
		LA18_: ;
		{
			nimln_(185, "unittest.nim");
			printf("%s%s%s%s%s\012", prefix? (prefix)->data:"nil", ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_19)? (((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_19))->data:"nil", reprEnum((NI)(*testResult).status, (&NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_))? (reprEnum((NI)(*testResult).status, (&NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_)))->data:"nil", ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_23)? (((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_23))->data:"nil", (*testResult).testName? ((*testResult).testName)->data:"nil");
			fflush(stdout);
		}
		LA14_: ;
	}
	LA7_: ;
	popFrame();
}

N_NIMCALL(void, suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter) {
	nimfr_("suiteEnded", "unittest.nim")
	nimln_(200, "unittest.nim");
	(*formatter).isInSuite = NIM_FALSE;
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NimStringDesc*, xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr_("xmlEscape", "unittest.nim")
	result = (NimStringDesc*)0;
	nimln_(203, "unittest.nim");
	result = rawNewString(((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		nimln_(3644, "system.nim");
		i = ((NI) 0);
		nimln_(3645, "system.nim");
		L = (s ? s->Sup.len : 0);
		{
			nimln_(3646, "system.nim");
			while (1) {
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_30;
				if (!(i < L)) goto LA3;
				nimln_(3647, "system.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				c = s->data[i];
				nimln_(205, "unittest.nim");
				switch (((NU8)(c))) {
				case 60:
				{
					nimln_(206, "unittest.nim");
					result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_24));
				}
				break;
				case 62:
				{
					nimln_(207, "unittest.nim");
					result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_25));
				}
				break;
				case 38:
				{
					nimln_(208, "unittest.nim");
					result = resizeString(result, 5);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_26));
				}
				break;
				case 34:
				{
					nimln_(209, "unittest.nim");
					result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_27));
				}
				break;
				case 39:
				{
					nimln_(210, "unittest.nim");
					result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_28));
				}
				break;
				default:
				{
					nimln_(212, "unittest.nim");
					{
						NimStringDesc* T14_;
						NimStringDesc* T15_;
						if (!(((NI) (((NU8)(c)))) < ((NI) 32))) goto LA12_;
						nimln_(213, "unittest.nim");
						T14_ = (NimStringDesc*)0;
						T15_ = (NimStringDesc*)0;
						T15_ = nimIntToStr(((NI) (((NU8)(c)))));
						T14_ = rawNewString(T15_->Sup.len + 3);
appendString(T14_, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_29));
appendString(T14_, T15_);
appendChar(T14_, 59);
						result = resizeString(result, T14_->Sup.len + 0);
appendString(result, T14_);
					}
					goto LA10_;
					LA12_: ;
					{
						nimln_(215, "unittest.nim");
						result = addChar(result, c);
					}
					LA10_: ;
				}
				break;
				}
				nimln_(3648, "system.nim");
				TM_Um3CQPZ9bILAIolZOsxNIaw_30 = addInt(i, ((NI) 1));
				i = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_30);
				nimln_(3649, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L))) goto LA19_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_31));
				}
				LA19_: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_TY_OU9b9b9b3svfAf0YBTEFQsJag)(void* p, NI op) {
	JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* a;
	a = (JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*)p;
	nimGCvisit((void*)(*a).stream, op);
	nimGCvisit((void*)(*a).testErrors, op);
	nimGCvisit((void*)(*a).testStackTrace, op);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_NIMCALL(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*, newJUnitOutputFormatter_PqqpGJPZVHC1k3JX9cfStQQ)(StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream) {
	JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* result;
	JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* T1_;
	NimStringDesc* T2_;
	nimfr_("newJUnitOutputFormatter", "unittest.nim")
	result = (JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*)0;
	nimln_(223, "unittest.nim");
	T1_ = (JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*)0;
	T1_ = (JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) newObj((&NTI_OU9b9b9b3svfAf0YBTEFQsJag_), sizeof(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ));
	(*T1_).Sup.Sup.m_type = (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_);
	asgnRef((void**) (&(*T1_).stream), stream);
	if ((*T1_).testErrors) nimGCunrefNoCycle((*T1_).testErrors);
	(*T1_).testErrors = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).testStackTrace; (*T1_).testStackTrace = copyStringRC1(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_15));
	if (T2_) nimGCunrefNoCycle(T2_);
	(*T1_).testStartTime = 0.0;
	result = T1_;
	nimln_(229, "unittest.nim");
	writeLine_G1TKFmud9akiH9bzSHWMshag_2(stream, TM_Um3CQPZ9bILAIolZOsxNIaw_33, 1);
	nimln_(230, "unittest.nim");
	writeLine_G1TKFmud9akiH9bzSHWMshag_2(stream, TM_Um3CQPZ9bILAIolZOsxNIaw_35, 1);
	popFrame();
	return result;
}

N_NIMCALL(void, close_EF53BADEiH9a6amiy7eitMg)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter) {
	nimfr_("close", "unittest.nim")
	nimln_(234, "unittest.nim");
	writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, TM_Um3CQPZ9bILAIolZOsxNIaw_37, 1);
	nimln_(235, "unittest.nim");
	close_4ed7IXme7lqtClFI7s2sTQ_2((*formatter).stream);
	popFrame();
}

N_NIMCALL(void, suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* suiteName) {
	TY_nHXaesL0DJZHyVS07ARPRA T1_;
	NimStringDesc* T2_;
	nimfr_("suiteStarted", "unittest.nim")
	nimln_(238, "unittest.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T2_ = (NimStringDesc*)0;
	T2_ = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ(suiteName);
	T1_[0] = nsuFormatSingleElem(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_39), T2_);
	writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, T1_, 1);
	popFrame();
}

N_NIMCALL(void, testStarted_EYS8dFM0pZmDNdV9c1cyo4Q)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "unittest.nim")
	nimln_(241, "unittest.nim");
	(*formatter).testErrors = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*formatter).testErrors)->Sup, sizeof(NimStringDesc*), ((NI) 0));
	nimln_(242, "unittest.nim");
	(*formatter).testStackTrace = setLengthStr((*formatter).testStackTrace, ((NI) 0));
	nimln_(243, "unittest.nim");
	(*formatter).testStartTime = ntepochTime();
	popFrame();
}

N_NIMCALL(void, failureOccurred_NAlHeCfOfz1bBvtw2rCPGw)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	nimfr_("failureOccurred", "unittest.nim")
	nimln_(248, "unittest.nim");
	add_sp11IzYl5roq19bn4qRQmqA((&(*formatter).testErrors), checkpoints->data, checkpoints->Sup.len);
	nimln_(249, "unittest.nim");
	{
		NimStringDesc* T5_;
		nimln_(364, "system.nim");
		nimln_(249, "unittest.nim");
		if (!!((stackTrace == NIM_NIL))) goto LA3_;
		nimln_(250, "unittest.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*formatter).testStackTrace; (*formatter).testStackTrace = copyStringRC1(stackTrace);
		if (T5_) nimGCunrefNoCycle(T5_);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, testEnded_E5f9a05hVCAPvYslPV2f4TQ)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult) {
	NF time_1;
	NF T1_;
	NimStringDesc* timeStr;
	TY_nHXaesL0DJZHyVS07ARPRA T2_;
	TY_Re75IspeoxXy2oCZHwcRrA T3_;
	nimfr_("testEnded", "unittest.nim")
	nimln_(253, "unittest.nim");
	T1_ = (NF)0;
	T1_ = ntepochTime();
	time_1 = ((NF)(T1_) - (NF)((*formatter).testStartTime));
	nimln_(254, "unittest.nim");
	timeStr = nsuformatFloat(time_1, ((FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ) 1), ((NI) 8), 46);
	nimln_(255, "unittest.nim");
	memset((void*)T2_, 0, sizeof(T2_));
	memset((void*)T3_, 0, sizeof(T3_));
	T3_[0] = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*testResult).testName);
	T3_[1] = copyString(timeStr);
	T2_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_40), T3_, 2);
	writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, T2_, 1);
	nimln_(256, "unittest.nim");
	switch ((*testResult).status) {
	case ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0):
	{
	}
	break;
	case ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 2):
	{
		nimln_(260, "unittest.nim");
		writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, TM_Um3CQPZ9bILAIolZOsxNIaw_41, 1);
	}
	break;
	case ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1):
	{
		NimStringDesc* failureMsg;
		NimStringDesc* errs;
		nimln_(262, "unittest.nim");
		{
			NIM_BOOL T9_;
			NI TM_Um3CQPZ9bILAIolZOsxNIaw_43;
			T9_ = (NIM_BOOL)0;
			T9_ = (((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0));
			if (!(T9_)) goto LA10_;
			nimln_(263, "unittest.nim");
			T9_ = (((NI) 0) < ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0));
			LA10_: ;
			if (!T9_) goto LA11_;
			nimln_(264, "unittest.nim");
			TM_Um3CQPZ9bILAIolZOsxNIaw_43 = subInt(((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0), ((NI) 1));
			if ((NU)((NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_43)) >= (NU)((*formatter).testErrors->Sup.len)) raiseIndexError();
			failureMsg = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*formatter).testErrors->data[(NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_43)]);
		}
		goto LA7_;
		LA11_: ;
		{
			nimln_(265, "unittest.nim");
			if (!(((NI) 0) < ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0))) goto LA14_;
			nimln_(266, "unittest.nim");
			if ((NU)(((NI) 0)) >= (NU)((*formatter).testErrors->Sup.len)) raiseIndexError();
			failureMsg = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*formatter).testErrors->data[((NI) 0)]);
		}
		goto LA7_;
		LA14_: ;
		{
			failureMsg = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_44));
		}
		LA7_: ;
		nimln_(269, "unittest.nim");
		errs = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_15));
		nimln_(270, "unittest.nim");
		{
			NI startIdx;
			NI endIdx;
			if (!(((NI) 1) < ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0))) goto LA19_;
			nimln_(271, "unittest.nim");
			{
				if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA23_;
				startIdx = ((NI) 0);
			}
			goto LA21_;
			LA23_: ;
			{
				startIdx = ((NI) 1);
			}
			LA21_: ;
			nimln_(272, "unittest.nim");
			{
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_45;
				if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA28_;
				TM_Um3CQPZ9bILAIolZOsxNIaw_45 = subInt(((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0), ((NI) 2));
				endIdx = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_45);
			}
			goto LA26_;
			LA28_: ;
			{
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_46;
				nimln_(273, "unittest.nim");
				TM_Um3CQPZ9bILAIolZOsxNIaw_46 = subInt(((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0), ((NI) 1));
				endIdx = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_46);
			}
			LA26_: ;
			{
				NI errIdx;
				NI res;
				errIdx = (NI)0;
				nimln_(1974, "system.nim");
				res = startIdx;
				{
					nimln_(1975, "system.nim");
					while (1) {
						NimStringDesc* T38_;
						NI TM_Um3CQPZ9bILAIolZOsxNIaw_47;
						if (!(res <= endIdx)) goto LA33;
						nimln_(1976, "system.nim");
						errIdx = res;
						nimln_(276, "unittest.nim");
						{
							if (!(((NI) 0) < (errs ? errs->Sup.len : 0))) goto LA36_;
							nimln_(277, "unittest.nim");
							errs = resizeString(errs, 1);
appendString(errs, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_13));
						}
						LA36_: ;
						nimln_(278, "unittest.nim");
						if ((NU)(errIdx) >= (NU)((*formatter).testErrors->Sup.len)) raiseIndexError();
						T38_ = (NimStringDesc*)0;
						T38_ = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*formatter).testErrors->data[errIdx]);
						errs = resizeString(errs, T38_->Sup.len + 0);
appendString(errs, T38_);
						nimln_(1977, "system.nim");
						TM_Um3CQPZ9bILAIolZOsxNIaw_47 = addInt(res, ((NI) 1));
						res = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_47);
					} LA33: ;
				}
			}
		}
		LA19_: ;
		nimln_(280, "unittest.nim");
		{
			TY_nHXaesL0DJZHyVS07ARPRA T43_;
			TY_Re75IspeoxXy2oCZHwcRrA T44_;
			if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA41_;
			nimln_(281, "unittest.nim");
			memset((void*)T43_, 0, sizeof(T43_));
			memset((void*)T44_, 0, sizeof(T44_));
			T44_[0] = copyString(failureMsg);
			T44_[1] = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*formatter).testStackTrace);
			T43_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_48), T44_, 2);
			writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, T43_, 1);
			nimln_(282, "unittest.nim");
			{
				TY_nHXaesL0DJZHyVS07ARPRA T49_;
				if (!(((NI) 0) < (errs ? errs->Sup.len : 0))) goto LA47_;
				nimln_(283, "unittest.nim");
				memset((void*)T49_, 0, sizeof(T49_));
				T49_[0] = nsuFormatSingleElem(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_49), errs);
				writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, T49_, 1);
			}
			LA47_: ;
		}
		goto LA39_;
		LA41_: ;
		{
			TY_nHXaesL0DJZHyVS07ARPRA T51_;
			TY_Re75IspeoxXy2oCZHwcRrA T52_;
			nimln_(285, "unittest.nim");
			memset((void*)T51_, 0, sizeof(T51_));
			memset((void*)T52_, 0, sizeof(T52_));
			T52_[0] = copyString(failureMsg);
			T52_[1] = copyString(errs);
			T51_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_50), T52_, 2);
			writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, T51_, 1);
		}
		LA39_: ;
	}
	break;
	}
	nimln_(287, "unittest.nim");
	writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, TM_Um3CQPZ9bILAIolZOsxNIaw_51, 1);
	popFrame();
}

N_NIMCALL(void, suiteEnded_EF53BADEiH9a6amiy7eitMg_2)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter) {
	nimfr_("suiteEnded", "unittest.nim")
	nimln_(290, "unittest.nim");
	writeLine_G1TKFmud9akiH9bzSHWMshag_2((*formatter).stream, TM_Um3CQPZ9bILAIolZOsxNIaw_53, 1);
	popFrame();
}

N_NIMCALL(NIM_BOOL, shouldRun_ONH9bpFQB7Lkusu9bdW9bZB9bg)(NimStringDesc* testName) {
	NIM_BOOL result;
	nimfr_("shouldRun", "unittest.nim")
	result = (NIM_BOOL)0;
	nimln_(293, "unittest.nim");
	result = NIM_TRUE;
	popFrame();
	return result;
}

N_NIMCALL(void, ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg)(void) {
	nimfr_("ensureFormattersInitialized", "unittest.nim")
	nimln_(296, "unittest.nim");
	{
		NIM_BOOL T3_;
		ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq__z9cxc4k8iqgnw41zdA8grdw(formatters_55U7g4zhjHV9bCI6emTgDiA, NIM_NIL);
		if (!T3_) goto LA4_;
		nimln_(297, "unittest.nim");
		if (formatters_55U7g4zhjHV9bCI6emTgDiA) nimGCunref(formatters_55U7g4zhjHV9bCI6emTgDiA);
		formatters_55U7g4zhjHV9bCI6emTgDiA = (TY_2gM6knqz8MaAY9c4MAR2ztg*) newSeqRC1((&NTI_2gM6knqz8MaAY9c4MAR2ztg_), 1);
		T6_ = (ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*)0;
		T6_ = defaultConsoleFormatter_5cci6OIDr79cInvvSsLn6vg();
		asgnRef((void**) (&formatters_55U7g4zhjHV9bCI6emTgDiA->data[0]), &T6_->Sup);
	}
	LA4_: ;
	popFrame();
}

N_NIMCALL(void, suiteEnded_8zybqvexf9aYkm9bmgyU3eLg_2)(void) {
	nimfr_("suiteEnded", "unittest.nim")
	{
		OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter;
		NI i;
		NI L;
		formatter = (OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*)0;
		nimln_(3626, "system.nim");
		i = ((NI) 0);
		nimln_(3627, "system.nim");
		L = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
		{
			nimln_(3628, "system.nim");
			while (1) {
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_55;
				if (!(i < L)) goto LA3;
				nimln_(3629, "system.nim");
				if ((NU)(i) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
				formatter = formatters_55U7g4zhjHV9bCI6emTgDiA->data[i];
				nimln_(303, "unittest.nim");
				suiteEnded_K2O75e2roACICAuYiNImyw(formatter);
				nimln_(3630, "system.nim");
				TM_Um3CQPZ9bILAIolZOsxNIaw_55 = addInt(i, ((NI) 1));
				i = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_55);
				nimln_(3631, "system.nim");
				{
					if (!!(((formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0) == L))) goto LA6_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_17));
				}
				LA6_: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, testEnded_xoIS1BdhYWQ6hhMP22XXiw)(TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult) {
	nimfr_("testEnded", "unittest.nim")
	{
		OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter;
		NI i;
		NI L;
		formatter = (OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*)0;
		nimln_(3626, "system.nim");
		i = ((NI) 0);
		nimln_(3627, "system.nim");
		L = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
		{
			nimln_(3628, "system.nim");
			while (1) {
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_56;
				if (!(i < L)) goto LA3;
				nimln_(3629, "system.nim");
				if ((NU)(i) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
				formatter = formatters_55U7g4zhjHV9bCI6emTgDiA->data[i];
				nimln_(307, "unittest.nim");
				testEnded_azSnnJ3hAiHHuUdLzViJlw(formatter, testResult);
				nimln_(3630, "system.nim");
				TM_Um3CQPZ9bILAIolZOsxNIaw_56 = addInt(i, ((NI) 1));
				i = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_56);
				nimln_(3631, "system.nim");
				{
					if (!!(((formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0) == L))) goto LA6_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_17));
				}
				LA6_: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, checkpoint_4nBz3prx9cKVVOoTZb4rNCQ)(NimStringDesc* msg) {
	NimStringDesc* T6_;
	nimfr_("checkpoint", "unittest.nim")
	nimln_(418, "unittest.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq__SRlIwYUUH1G46Yee9aMIFAQ(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, NIM_NIL);
		if (!T3_) goto LA4_;
		nimln_(419, "unittest.nim");
		if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
		checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	}
	LA4_: ;
	nimln_(420, "unittest.nim");
	checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ)->Sup, sizeof(NimStringDesc*));
	T6_ = (NimStringDesc*)0;
	T6_ = checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ->data[checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ->Sup.len]; checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ->data[checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ->Sup.len] = copyStringRC1(msg);
	if (T6_) nimGCunrefNoCycle(T6_);
	++checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ->Sup.len;
	popFrame();
}

static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQunittest)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;
	nimfr_("find", "system.nim")
{	result = (NI)0;
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2066, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2067, "system.nim");
			while (1) {
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_57;
				NI TM_Um3CQPZ9bILAIolZOsxNIaw_58;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2068, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2300, "system.nim");
				{
					if (!eqStrings(i, item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2301, "system.nim");
				TM_Um3CQPZ9bILAIolZOsxNIaw_57 = addInt(result, ((NI) 1));
				result = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_57);
				nimln_(2069, "system.nim");
				TM_Um3CQPZ9bILAIolZOsxNIaw_58 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_Um3CQPZ9bILAIolZOsxNIaw_58);
			} LA3: ;
		}
	}
	nimln_(2302, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwunittest)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim")
{	result = (NIM_BOOL)0;
	nimln_(2307, "system.nim");
	T1_ = (NI)0;
	T1_ = find_9basNl9bVqn7SOf9bgUeI8TEQunittest(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_unittestInit000)(void) {
	nimfr_("unittest", "unittest.nim")
nimRegisterGlobalMarker(TM_Um3CQPZ9bILAIolZOsxNIaw_2);
nimRegisterGlobalMarker(TM_Um3CQPZ9bILAIolZOsxNIaw_3);
	nimln_(116, "unittest.nim");
	abortOnError_Bte3Uiwc4Q19ago2N4C89cUA = existsEnv_ahpnHkfRE9cLlJNaRpEL7Vw(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_4));
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_unittestDatInit000)(void) {
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_5[4];
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_6[3];
NI TM_Um3CQPZ9bILAIolZOsxNIaw_8;
static char* NIM_CONST TM_Um3CQPZ9bILAIolZOsxNIaw_7[3] = {
"PRINT_ALL", 
"PRINT_FAILURES", 
"PRINT_NONE"};
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_20[3];
NI TM_Um3CQPZ9bILAIolZOsxNIaw_22;
static char* NIM_CONST TM_Um3CQPZ9bILAIolZOsxNIaw_21[3] = {
"OK", 
"FAILED", 
"SKIPPED"};
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_32[4];
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_59[3];
static TNimNode TM_Um3CQPZ9bILAIolZOsxNIaw_0[23];
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.size = sizeof(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw);
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.kind = 17;
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.flags = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[0].len = 0; TM_Um3CQPZ9bILAIolZOsxNIaw_0[0].kind = 2;
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[0];
NTI_po6hYFavJCZm28qf1dR3mw_.size = sizeof(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*);
NTI_po6hYFavJCZm28qf1dR3mw_.kind = 22;
NTI_po6hYFavJCZm28qf1dR3mw_.base = (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_);
NTI_po6hYFavJCZm28qf1dR3mw_.marker = Marker_TY_po6hYFavJCZm28qf1dR3mw;
NTI_2gM6knqz8MaAY9c4MAR2ztg_.size = sizeof(TY_2gM6knqz8MaAY9c4MAR2ztg*);
NTI_2gM6knqz8MaAY9c4MAR2ztg_.kind = 24;
NTI_2gM6knqz8MaAY9c4MAR2ztg_.base = (&NTI_po6hYFavJCZm28qf1dR3mw_);
NTI_2gM6knqz8MaAY9c4MAR2ztg_.marker = Marker_TY_2gM6knqz8MaAY9c4MAR2ztg;
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.size = sizeof(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw);
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.kind = 17;
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.base = (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_);
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.flags = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_5[0] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[2];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[2].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[2].offset = offsetof(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, colorOutput);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[2].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[2].name = "colorOutput";
TM_Um3CQPZ9bILAIolZOsxNIaw_5[1] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[3];
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.size = sizeof(OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww);
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.kind = 14;
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.base = 0;
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.flags = 3;
for (TM_Um3CQPZ9bILAIolZOsxNIaw_8 = 0; TM_Um3CQPZ9bILAIolZOsxNIaw_8 < 3; TM_Um3CQPZ9bILAIolZOsxNIaw_8++) {
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_8+4].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_8+4].offset = TM_Um3CQPZ9bILAIolZOsxNIaw_8;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_8+4].name = TM_Um3CQPZ9bILAIolZOsxNIaw_7[TM_Um3CQPZ9bILAIolZOsxNIaw_8];
TM_Um3CQPZ9bILAIolZOsxNIaw_6[TM_Um3CQPZ9bILAIolZOsxNIaw_8] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_8+4];
}
TM_Um3CQPZ9bILAIolZOsxNIaw_0[7].len = 3; TM_Um3CQPZ9bILAIolZOsxNIaw_0[7].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[7].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_6[0];
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[7];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[3].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[3].offset = offsetof(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, outputLevel);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[3].typ = (&NTI_7UfTrIPsm9cGDPwH9bpwJDww_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[3].name = "outputLevel";
TM_Um3CQPZ9bILAIolZOsxNIaw_5[2] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[8];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].offset = offsetof(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, isInSuite);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].name = "isInSuite";
TM_Um3CQPZ9bILAIolZOsxNIaw_5[3] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[9];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].offset = offsetof(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, isInTest);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].name = "isInTest";
TM_Um3CQPZ9bILAIolZOsxNIaw_0[1].len = 4; TM_Um3CQPZ9bILAIolZOsxNIaw_0[1].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[1].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_5[0];
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[1];
NTI_ExFEz8ninaqkX3e4eolu7g_.size = sizeof(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*);
NTI_ExFEz8ninaqkX3e4eolu7g_.kind = 22;
NTI_ExFEz8ninaqkX3e4eolu7g_.base = (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_);
NTI_ExFEz8ninaqkX3e4eolu7g_.marker = Marker_TY_ExFEz8ninaqkX3e4eolu7g;
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.size = sizeof(TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ);
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.kind = 14;
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.base = 0;
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.flags = 3;
for (TM_Um3CQPZ9bILAIolZOsxNIaw_22 = 0; TM_Um3CQPZ9bILAIolZOsxNIaw_22 < 3; TM_Um3CQPZ9bILAIolZOsxNIaw_22++) {
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_22+10].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_22+10].offset = TM_Um3CQPZ9bILAIolZOsxNIaw_22;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_22+10].name = TM_Um3CQPZ9bILAIolZOsxNIaw_21[TM_Um3CQPZ9bILAIolZOsxNIaw_22];
TM_Um3CQPZ9bILAIolZOsxNIaw_20[TM_Um3CQPZ9bILAIolZOsxNIaw_22] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_22+10];
}
TM_Um3CQPZ9bILAIolZOsxNIaw_0[13].len = 3; TM_Um3CQPZ9bILAIolZOsxNIaw_0[13].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[13].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_20[0];
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[13];
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.size = sizeof(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ);
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.kind = 17;
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.base = (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_);
TM_Um3CQPZ9bILAIolZOsxNIaw_32[0] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[15];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[15].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[15].offset = offsetof(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, stream);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[15].typ = (&NTI_r3Wc5tOoxP8rz1DvGVTUvw_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[15].name = "stream";
TM_Um3CQPZ9bILAIolZOsxNIaw_32[1] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[16];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[16].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[16].offset = offsetof(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, testErrors);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[16].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[16].name = "testErrors";
TM_Um3CQPZ9bILAIolZOsxNIaw_32[2] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[17];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].offset = offsetof(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, testStartTime);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].name = "testStartTime";
TM_Um3CQPZ9bILAIolZOsxNIaw_32[3] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[18];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].offset = offsetof(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, testStackTrace);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].name = "testStackTrace";
TM_Um3CQPZ9bILAIolZOsxNIaw_0[14].len = 4; TM_Um3CQPZ9bILAIolZOsxNIaw_0[14].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[14].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_32[0];
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[14];
NTI_OU9b9b9b3svfAf0YBTEFQsJag_.size = sizeof(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*);
NTI_OU9b9b9b3svfAf0YBTEFQsJag_.kind = 22;
NTI_OU9b9b9b3svfAf0YBTEFQsJag_.base = (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_);
NTI_OU9b9b9b3svfAf0YBTEFQsJag_.marker = Marker_TY_OU9b9b9b3svfAf0YBTEFQsJag;
NTI_GEvSVSxdPWWgMGM48ywEYQ_.size = sizeof(TestResult_GEvSVSxdPWWgMGM48ywEYQ);
NTI_GEvSVSxdPWWgMGM48ywEYQ_.kind = 18;
NTI_GEvSVSxdPWWgMGM48ywEYQ_.base = 0;
NTI_GEvSVSxdPWWgMGM48ywEYQ_.flags = 2;
TM_Um3CQPZ9bILAIolZOsxNIaw_59[0] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[20];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[20].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[20].offset = offsetof(TestResult_GEvSVSxdPWWgMGM48ywEYQ, suiteName);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[20].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[20].name = "suiteName";
TM_Um3CQPZ9bILAIolZOsxNIaw_59[1] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[21];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[21].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[21].offset = offsetof(TestResult_GEvSVSxdPWWgMGM48ywEYQ, testName);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[21].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[21].name = "testName";
TM_Um3CQPZ9bILAIolZOsxNIaw_59[2] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[22];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[22].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[22].offset = offsetof(TestResult_GEvSVSxdPWWgMGM48ywEYQ, status);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[22].typ = (&NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[22].name = "status";
TM_Um3CQPZ9bILAIolZOsxNIaw_0[19].len = 3; TM_Um3CQPZ9bILAIolZOsxNIaw_0[19].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[19].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_59[0];
NTI_GEvSVSxdPWWgMGM48ywEYQ_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[19];
}

