/* Generated by Nim Compiler v0.17.1 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/p/Nim/lib -o /p/calendars/test/nimcache/stdlib_terminal.o /p/calendars/test/nimcache/stdlib_terminal.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <termios.h>
#include <string.h>
#include <stdio.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <unistd.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY_1v9bKyksXWMsm0vNwmZ4EuQ TY_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef unsigned char TY_KJ4qKxW1tMgxmwqh7LkftA[20];
struct IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA {
unsigned short ws_row;
unsigned short ws_col;
unsigned short ws_xpixel;
unsigned short ws_ypixel;
};
typedef NI TY_Bd4h7Ocx9bGTvrKzPIWNlHw[3];
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI TY_GAcaPw08Gj9cXYhAaMMr9cfw[1];
struct TY_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef NU8 Style_NXKayqTLMsAibFwNceBlpA_Set;
typedef NU8 Style_NXKayqTLMsAibFwNceBlpA;
typedef NU8 ForegroundColor_ez9ah4IgQc0AbdW68acioDg;
typedef NU8 BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA;
N_NIMCALL(void, setRaw_bWuPmHcnrBG1QQlDC4s7ug)(int fd, int time_0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ)(NI* fds, NI fdsLen_0);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2)(NI* fds, NI fdsLen_0);
N_NIMCALL(NI, terminalWidth_Tjr5MOdj42hdx5sjNUiDXw)(void);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, getEnv_8zNgT9bxx7m9cTt2TeVdTdIw)(NimStringDesc* key);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
N_NIMCALL(NI, terminalHeight_Tjr5MOdj42hdx5sjNUiDXw_2)(void);
N_NIMCALL(TY_1v9bKyksXWMsm0vNwmZ4EuQ, terminalSize_xv1ti3xUvO9cxOT8Iw8Silg)(void);
N_NIMCALL(void, hideCursor_tFIu39aFSR3N0M64Ynwugng)(FILE* f);
N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_NIMCALL(void, showCursor_tFIu39aFSR3N0M64Ynwugng_2)(FILE* f);
N_NIMCALL(void, setCursorPos_UIoIgoUReHcDarvfaNRl3A)(FILE* f, NI x, NI y);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, setCursorXPos_xCTglc09c1SJqpnj2xD1oSQ)(FILE* f, NI x);
N_NIMCALL(void, cursorUp_KTh8Z5dlyNBmCQ1i9aGXTzg)(FILE* f, NI count);
N_NIMCALL(void, cursorDown_KTh8Z5dlyNBmCQ1i9aGXTzg_2)(FILE* f, NI count);
N_NIMCALL(void, cursorForward_KTh8Z5dlyNBmCQ1i9aGXTzg_3)(FILE* f, NI count);
N_NIMCALL(void, cursorBackward_KTh8Z5dlyNBmCQ1i9aGXTzg_4)(FILE* f, NI count);
N_NIMCALL(void, eraseLine_tFIu39aFSR3N0M64Ynwugng_3)(FILE* f);
N_NIMCALL(void, eraseScreen_tFIu39aFSR3N0M64Ynwugng_4)(FILE* f);
N_NIMCALL(void, resetAttributes_tFIu39aFSR3N0M64Ynwugng_5)(FILE* f);
N_NIMCALL(void, setStyle_zEKKPPIjKZs9bVYu4TwenLg)(FILE* f, Style_NXKayqTLMsAibFwNceBlpA_Set style);
N_NIMCALL(void, writeStyled_jPzCz3P0CaIFIvdlX9aQd4w)(NimStringDesc* txt, Style_NXKayqTLMsAibFwNceBlpA_Set style);
N_NIMCALL(void, setForegroundColor_Tw7yxMupneOmAicqiYt3NA)(FILE* f, ForegroundColor_ez9ah4IgQc0AbdW68acioDg fg, NIM_BOOL bright);
N_NIMCALL(void, setBackgroundColor_6SjySiY3ji4zTKKPgtXoig)(FILE* f, BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA bg, NIM_BOOL bright);
N_NIMCALL(NIM_BOOL, isatty_POoHvosCWg3Yl5ieYeLHrg)(FILE* f);
N_NIMCALL(int, getFileHandle_bZ9c2yojtXoDTUpfyl8h8Rg)(FILE* f);
N_NIMCALL(NIM_CHAR, getch_PZUNldkwV2VhZMU6UCrZTA)(void);
N_NIMCALL(NIM_CHAR, readChar_ufPUIQ2Rg4xhWjWigciDOg)(FILE* f);
N_NOCONV(void, resetAttributes_1y1Orb5p0KBhRdFFLR9bNtg)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NI gFG_g7w4T3anr20OMlWloNx2tQ;
NI gBG_dgmeknpHWrtwqMJGQAp9atA;
NIM_CONST TY_Bd4h7Ocx9bGTvrKzPIWNlHw TM_CN3raB9atujkEiPpxYAdlgQ_4 = {((NI) 0),
((NI) 1),
((NI) 2)}
;
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_5, "COLUMNS", 7);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_6, "LINES", 5);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_7, "\033[\?25l", 6);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_8, "\033[\?25h", 6);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_9, "\033[", 2);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_10, "\033[2K", 4);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_11, "\033[2J", 4);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_12, "\033[0m", 4);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, setRaw_bWuPmHcnrBG1QQlDC4s7ug)(int fd, int time_0) {
	struct termios mode;
	int T1_;
	int T2_;
	nimfr_("setRaw", "terminal.nim")
	memset((void*)(&mode), 0, sizeof(mode));
	nimln_(176, "terminal.nim");
	T1_ = (int)0;
	T1_ = tcgetattr(fd, (&mode));
	T1_;
	nimln_(177, "terminal.nim");
	mode.c_iflag = (unsigned int)(mode.c_iflag & (unsigned int)((NU32) ~((unsigned int)((unsigned int)((unsigned int)((unsigned int)(BRKINT | ICRNL) | INPCK) | ISTRIP) | IXON))));
	nimln_(179, "terminal.nim");
	mode.c_oflag = (unsigned int)(mode.c_oflag & (unsigned int)((NU32) ~(OPOST)));
	nimln_(180, "terminal.nim");
	mode.c_cflag = (unsigned int)((unsigned int)(mode.c_cflag & (unsigned int)((NU32) ~((unsigned int)(CSIZE | PARENB)))) | CS8);
	nimln_(181, "terminal.nim");
	mode.c_lflag = (unsigned int)(mode.c_lflag & (unsigned int)((NU32) ~((unsigned int)((unsigned int)((unsigned int)(ECHO | ICANON) | IEXTEN) | ISIG))));
	if ((NU)(VMIN) > (NU)(19)) raiseIndexError();
	nimln_(182, "terminal.nim");
	mode.c_cc[(VMIN)- 0] = 1;
	if ((NU)(VTIME) > (NU)(19)) raiseIndexError();
	nimln_(183, "terminal.nim");
	mode.c_cc[(VTIME)- 0] = 0;
	nimln_(184, "terminal.nim");
	T2_ = (int)0;
	T2_ = tcsetattr(fd, time_0, (&mode));
	T2_;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NI, terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ)(NI* fds, NI fdsLen_0) {
	NI result;
	IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA win;
	nimfr_("terminalWidthIoctl", "terminal.nim")
{	result = (NI)0;
	memset((void*)(&win), 0, sizeof(win));
	{
		NI fd;
		NI i;
		fd = (NI)0;
		nimln_(2066, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2067, "system.nim");
			while (1) {
				NI TM_CN3raB9atujkEiPpxYAdlgQ_2;
				if (!(i < fdsLen_0)) goto LA3;
				nimln_(2068, "system.nim");
				if ((NU)(i) >= (NU)(fdsLen_0)) raiseIndexError();
				fd = fds[i];
				nimln_(191, "terminal.nim");
				{
					NI T6_;
					nimln_(364, "system.nim");
					nimln_(191, "terminal.nim");
					T6_ = (NI)0;
					T6_ = ioctl(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))), TIOCGWINSZ, (&win));
					if (!!((T6_ == ((NI) -1)))) goto LA7_;
					nimln_(192, "terminal.nim");
					result = ((NI) (win.ws_col));
					goto BeforeRet_;
				}
				LA7_: ;
				nimln_(2069, "system.nim");
				TM_CN3raB9atujkEiPpxYAdlgQ_2 = addInt(i, ((NI) 1));
				i = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_2);
			} LA3: ;
		}
	}
	nimln_(193, "terminal.nim");
	result = ((NI) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2)(NI* fds, NI fdsLen_0) {
	NI result;
	IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA win;
	nimfr_("terminalHeightIoctl", "terminal.nim")
{	result = (NI)0;
	memset((void*)(&win), 0, sizeof(win));
	{
		NI fd;
		NI i;
		fd = (NI)0;
		nimln_(2066, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2067, "system.nim");
			while (1) {
				NI TM_CN3raB9atujkEiPpxYAdlgQ_3;
				if (!(i < fdsLen_0)) goto LA3;
				nimln_(2068, "system.nim");
				if ((NU)(i) >= (NU)(fdsLen_0)) raiseIndexError();
				fd = fds[i];
				nimln_(200, "terminal.nim");
				{
					NI T6_;
					nimln_(364, "system.nim");
					nimln_(200, "terminal.nim");
					T6_ = (NI)0;
					T6_ = ioctl(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))), TIOCGWINSZ, (&win));
					if (!!((T6_ == ((NI) -1)))) goto LA7_;
					nimln_(201, "terminal.nim");
					result = ((NI) (win.ws_row));
					goto BeforeRet_;
				}
				LA7_: ;
				nimln_(2069, "system.nim");
				TM_CN3raB9atujkEiPpxYAdlgQ_3 = addInt(i, ((NI) 1));
				i = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_3);
			} LA3: ;
		}
	}
	nimln_(202, "terminal.nim");
	result = ((NI) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, terminalWidth_Tjr5MOdj42hdx5sjNUiDXw)(void) {
	NI result;
	NI w;
	NimStringDesc* cterm;
	int fd;
	NCSTRING T5_;
	int T11_;
	NimStringDesc* s;
	nimfr_("terminalWidth", "terminal.nim")
{	result = (NI)0;
	nimln_(210, "terminal.nim");
	w = terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ(TM_CN3raB9atujkEiPpxYAdlgQ_4, 3);
	nimln_(211, "terminal.nim");
	{
		if (!(((NI) 0) < w)) goto LA3_;
		result = w;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(212, "terminal.nim");
	cterm = mnewString(((NI)chckRange(L_ctermid, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(213, "terminal.nim");
	T5_ = (NCSTRING)0;
	T5_ = ctermid(cterm->data);
	fd = open(T5_, O_RDONLY);
	nimln_(214, "terminal.nim");
	{
		TY_GAcaPw08Gj9cXYhAaMMr9cfw T10_;
		nimln_(364, "system.nim");
		nimln_(214, "terminal.nim");
		if (!!((fd == ((NI32) -1)))) goto LA8_;
		nimln_(215, "terminal.nim");
		T10_[0] = ((NI) (fd));
		w = terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ(T10_, 1);
	}
	LA8_: ;
	nimln_(216, "terminal.nim");
	T11_ = (int)0;
	T11_ = close(fd);
	T11_;
	nimln_(217, "terminal.nim");
	{
		if (!(((NI) 0) < w)) goto LA14_;
		result = w;
		goto BeforeRet_;
	}
	LA14_: ;
	nimln_(218, "terminal.nim");
	s = getEnv_8zNgT9bxx7m9cTt2TeVdTdIw(((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_5));
	nimln_(219, "terminal.nim");
	{
		NIM_BOOL T18_;
		NIM_BOOL T19_;
		NI T21_;
		T18_ = (NIM_BOOL)0;
		T19_ = (NIM_BOOL)0;
		T19_ = (((NI) 0) < (s ? s->Sup.len : 0));
		if (!(T19_)) goto LA20_;
		T21_ = (NI)0;
		T21_ = npuParseInt(s, (&w), ((NI) 0));
		T19_ = (((NI) 0) < T21_);
		LA20_: ;
		T18_ = T19_;
		if (!(T18_)) goto LA22_;
		T18_ = (((NI) 0) < w);
		LA22_: ;
		if (!T18_) goto LA23_;
		nimln_(220, "terminal.nim");
		result = w;
		goto BeforeRet_;
	}
	LA23_: ;
	nimln_(221, "terminal.nim");
	result = ((NI) 80);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, terminalHeight_Tjr5MOdj42hdx5sjNUiDXw_2)(void) {
	NI result;
	NI h;
	NimStringDesc* cterm;
	int fd;
	NCSTRING T5_;
	int T11_;
	NimStringDesc* s;
	nimfr_("terminalHeight", "terminal.nim")
{	result = (NI)0;
	nimln_(228, "terminal.nim");
	h = terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2(TM_CN3raB9atujkEiPpxYAdlgQ_4, 3);
	nimln_(229, "terminal.nim");
	{
		if (!(((NI) 0) < h)) goto LA3_;
		result = h;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(230, "terminal.nim");
	cterm = mnewString(((NI)chckRange(L_ctermid, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(231, "terminal.nim");
	T5_ = (NCSTRING)0;
	T5_ = ctermid(cterm->data);
	fd = open(T5_, O_RDONLY);
	nimln_(232, "terminal.nim");
	{
		TY_GAcaPw08Gj9cXYhAaMMr9cfw T10_;
		nimln_(364, "system.nim");
		nimln_(232, "terminal.nim");
		if (!!((fd == ((NI32) -1)))) goto LA8_;
		nimln_(233, "terminal.nim");
		T10_[0] = ((NI) (fd));
		h = terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2(T10_, 1);
	}
	LA8_: ;
	nimln_(234, "terminal.nim");
	T11_ = (int)0;
	T11_ = close(fd);
	T11_;
	nimln_(235, "terminal.nim");
	{
		if (!(((NI) 0) < h)) goto LA14_;
		result = h;
		goto BeforeRet_;
	}
	LA14_: ;
	nimln_(236, "terminal.nim");
	s = getEnv_8zNgT9bxx7m9cTt2TeVdTdIw(((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_6));
	nimln_(237, "terminal.nim");
	{
		NIM_BOOL T18_;
		NIM_BOOL T19_;
		NI T21_;
		T18_ = (NIM_BOOL)0;
		T19_ = (NIM_BOOL)0;
		T19_ = (((NI) 0) < (s ? s->Sup.len : 0));
		if (!(T19_)) goto LA20_;
		T21_ = (NI)0;
		T21_ = npuParseInt(s, (&h), ((NI) 0));
		T19_ = (((NI) 0) < T21_);
		LA20_: ;
		T18_ = T19_;
		if (!(T18_)) goto LA22_;
		T18_ = (((NI) 0) < h);
		LA22_: ;
		if (!T18_) goto LA23_;
		nimln_(238, "terminal.nim");
		result = h;
		goto BeforeRet_;
	}
	LA23_: ;
	nimln_(239, "terminal.nim");
	result = ((NI) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(TY_1v9bKyksXWMsm0vNwmZ4EuQ, terminalSize_xv1ti3xUvO9cxOT8Iw8Silg)(void) {
	TY_1v9bKyksXWMsm0vNwmZ4EuQ result;
	nimfr_("terminalSize", "terminal.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln_(244, "terminal.nim");
	result.Field0 = terminalWidth_Tjr5MOdj42hdx5sjNUiDXw();
	result.Field1 = terminalHeight_Tjr5MOdj42hdx5sjNUiDXw_2();
	popFrame();
	return result;
}

N_NIMCALL(void, hideCursor_tFIu39aFSR3N0M64Ynwugng)(FILE* f) {
	nimfr_("hideCursor", "terminal.nim")
	nimln_(261, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_7));
	popFrame();
}

N_NIMCALL(void, showCursor_tFIu39aFSR3N0M64Ynwugng_2)(FILE* f) {
	nimfr_("showCursor", "terminal.nim")
	nimln_(268, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_8));
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(void, setCursorPos_UIoIgoUReHcDarvfaNRl3A)(FILE* f, NI x, NI y) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	nimfr_("setCursorPos", "terminal.nim")
	nimln_(277, "terminal.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr(y);
	T3_ = (NimStringDesc*)0;
	T3_ = nimIntToStr(x);
	T1_ = rawNewString(T2_->Sup.len + T3_->Sup.len + 4);
appendString(T1_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
appendString(T1_, T2_);
appendChar(T1_, 59);
appendString(T1_, T3_);
appendChar(T1_, 102);
	write_c4mGyJBvK73pdM22jiweKQ(f, T1_);
	popFrame();
}

N_NIMCALL(void, setCursorXPos_xCTglc09c1SJqpnj2xD1oSQ)(FILE* f, NI x) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("setCursorXPos", "terminal.nim")
	nimln_(292, "terminal.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr(x);
	T1_ = rawNewString(T2_->Sup.len + 3);
appendString(T1_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
appendString(T1_, T2_);
appendChar(T1_, 71);
	write_c4mGyJBvK73pdM22jiweKQ(f, T1_);
	popFrame();
}

N_NIMCALL(void, cursorUp_KTh8Z5dlyNBmCQ1i9aGXTzg)(FILE* f, NI count) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("cursorUp", "terminal.nim")
	nimln_(319, "terminal.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr(count);
	T1_ = rawNewString(T2_->Sup.len + 3);
appendString(T1_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
appendString(T1_, T2_);
appendChar(T1_, 65);
	write_c4mGyJBvK73pdM22jiweKQ(f, T1_);
	popFrame();
}

N_NIMCALL(void, cursorDown_KTh8Z5dlyNBmCQ1i9aGXTzg_2)(FILE* f, NI count) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("cursorDown", "terminal.nim")
	nimln_(329, "terminal.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr(count);
	T1_ = rawNewString(T2_->Sup.len + 3);
appendString(T1_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
appendString(T1_, T2_);
appendChar(T1_, 66);
	write_c4mGyJBvK73pdM22jiweKQ(f, T1_);
	popFrame();
}

N_NIMCALL(void, cursorForward_KTh8Z5dlyNBmCQ1i9aGXTzg_3)(FILE* f, NI count) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("cursorForward", "terminal.nim")
	nimln_(339, "terminal.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr(count);
	T1_ = rawNewString(T2_->Sup.len + 3);
appendString(T1_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
appendString(T1_, T2_);
appendChar(T1_, 67);
	write_c4mGyJBvK73pdM22jiweKQ(f, T1_);
	popFrame();
}

N_NIMCALL(void, cursorBackward_KTh8Z5dlyNBmCQ1i9aGXTzg_4)(FILE* f, NI count) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("cursorBackward", "terminal.nim")
	nimln_(349, "terminal.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr(count);
	T1_ = rawNewString(T2_->Sup.len + 3);
appendString(T1_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
appendString(T1_, T2_);
appendChar(T1_, 68);
	write_c4mGyJBvK73pdM22jiweKQ(f, T1_);
	popFrame();
}

N_NIMCALL(void, eraseLine_tFIu39aFSR3N0M64Ynwugng_3)(FILE* f) {
	nimfr_("eraseLine", "terminal.nim")
	nimln_(403, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_10));
	nimln_(404, "terminal.nim");
	setCursorXPos_xCTglc09c1SJqpnj2xD1oSQ(f, ((NI) 0));
	popFrame();
}

N_NIMCALL(void, eraseScreen_tFIu39aFSR3N0M64Ynwugng_4)(FILE* f) {
	nimfr_("eraseScreen", "terminal.nim")
	nimln_(426, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_11));
	popFrame();
}

N_NIMCALL(void, resetAttributes_tFIu39aFSR3N0M64Ynwugng_5)(FILE* f) {
	nimfr_("resetAttributes", "terminal.nim")
	nimln_(436, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_12));
	popFrame();
}

N_NIMCALL(void, setStyle_zEKKPPIjKZs9bVYu4TwenLg)(FILE* f, Style_NXKayqTLMsAibFwNceBlpA_Set style) {
	nimfr_("setStyle", "terminal.nim")
	{
		Style_NXKayqTLMsAibFwNceBlpA s;
		NI i;
		s = (Style_NXKayqTLMsAibFwNceBlpA)0;
		nimln_(2100, "system.nim");
		i = ((NI) 1);
		{
			nimln_(2101, "system.nim");
			while (1) {
				NI TM_CN3raB9atujkEiPpxYAdlgQ_13;
				if (!(i <= ((NI) 8))) goto LA3;
				nimln_(2102, "system.nim");
				{
					NimStringDesc* T8_;
					NimStringDesc* T9_;
					if (!((style &(1U<<((NU)((((Style_NXKayqTLMsAibFwNceBlpA)chckRange(i, ((Style_NXKayqTLMsAibFwNceBlpA) 1), ((Style_NXKayqTLMsAibFwNceBlpA) 8)))- 1))&7U)))!=0)) goto LA6_;
					s = ((Style_NXKayqTLMsAibFwNceBlpA)chckRange(i, ((Style_NXKayqTLMsAibFwNceBlpA) 1), ((Style_NXKayqTLMsAibFwNceBlpA) 8)));
					nimln_(469, "terminal.nim");
					T8_ = (NimStringDesc*)0;
					T9_ = (NimStringDesc*)0;
					T9_ = nimIntToStr(((NI) (s)));
					T8_ = rawNewString(T9_->Sup.len + 3);
appendString(T8_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
appendString(T8_, T9_);
appendChar(T8_, 109);
					write_c4mGyJBvK73pdM22jiweKQ(f, T8_);
				}
				LA6_: ;
				nimln_(2103, "system.nim");
				TM_CN3raB9atujkEiPpxYAdlgQ_13 = addInt(i, ((NI) 1));
				i = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_13);
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, writeStyled_jPzCz3P0CaIFIvdlX9aQd4w)(NimStringDesc* txt, Style_NXKayqTLMsAibFwNceBlpA_Set style) {
	nimfr_("writeStyled", "terminal.nim")
	nimln_(479, "terminal.nim");
	setStyle_zEKKPPIjKZs9bVYu4TwenLg(stdout, style);
	nimln_(480, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(stdout, txt);
	nimln_(481, "terminal.nim");
	resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
	nimln_(482, "terminal.nim");
	{
		NimStringDesc* T5_;
		NimStringDesc* T6_;
		nimln_(364, "system.nim");
		nimln_(482, "terminal.nim");
		if (!!((gFG_g7w4T3anr20OMlWloNx2tQ == ((NI) 0)))) goto LA3_;
		nimln_(483, "terminal.nim");
		T5_ = (NimStringDesc*)0;
		T6_ = (NimStringDesc*)0;
		T6_ = nimIntToStr(((NI) (gFG_g7w4T3anr20OMlWloNx2tQ)));
		T5_ = rawNewString(T6_->Sup.len + 3);
appendString(T5_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
appendString(T5_, T6_);
appendChar(T5_, 109);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, T5_);
	}
	LA3_: ;
	nimln_(484, "terminal.nim");
	{
		NimStringDesc* T11_;
		NimStringDesc* T12_;
		nimln_(364, "system.nim");
		nimln_(484, "terminal.nim");
		if (!!((gBG_dgmeknpHWrtwqMJGQAp9atA == ((NI) 0)))) goto LA9_;
		nimln_(485, "terminal.nim");
		T11_ = (NimStringDesc*)0;
		T12_ = (NimStringDesc*)0;
		T12_ = nimIntToStr(((NI) (gBG_dgmeknpHWrtwqMJGQAp9atA)));
		T11_ = rawNewString(T12_->Sup.len + 3);
appendString(T11_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
appendString(T11_, T12_);
appendChar(T11_, 109);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, T11_);
	}
	LA9_: ;
	popFrame();
}

N_NIMCALL(void, setForegroundColor_Tw7yxMupneOmAicqiYt3NA)(FILE* f, ForegroundColor_ez9ah4IgQc0AbdW68acioDg fg, NIM_BOOL bright) {
	NimStringDesc* T5_;
	NimStringDesc* T6_;
	nimfr_("setForegroundColor", "terminal.nim")
	nimln_(529, "terminal.nim");
	gFG_g7w4T3anr20OMlWloNx2tQ = ((NI) (fg));
	nimln_(530, "terminal.nim");
	{
		NI TM_CN3raB9atujkEiPpxYAdlgQ_14;
		if (!bright) goto LA3_;
		TM_CN3raB9atujkEiPpxYAdlgQ_14 = addInt(gFG_g7w4T3anr20OMlWloNx2tQ, ((NI) 60));
		gFG_g7w4T3anr20OMlWloNx2tQ = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_14);
	}
	LA3_: ;
	nimln_(531, "terminal.nim");
	T5_ = (NimStringDesc*)0;
	T6_ = (NimStringDesc*)0;
	T6_ = nimIntToStr(gFG_g7w4T3anr20OMlWloNx2tQ);
	T5_ = rawNewString(T6_->Sup.len + 3);
appendString(T5_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
appendString(T5_, T6_);
appendChar(T5_, 109);
	write_c4mGyJBvK73pdM22jiweKQ(f, T5_);
	popFrame();
}

N_NIMCALL(void, setBackgroundColor_6SjySiY3ji4zTKKPgtXoig)(FILE* f, BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA bg, NIM_BOOL bright) {
	NimStringDesc* T5_;
	NimStringDesc* T6_;
	nimfr_("setBackgroundColor", "terminal.nim")
	nimln_(551, "terminal.nim");
	gBG_dgmeknpHWrtwqMJGQAp9atA = ((NI) (bg));
	nimln_(552, "terminal.nim");
	{
		NI TM_CN3raB9atujkEiPpxYAdlgQ_15;
		if (!bright) goto LA3_;
		TM_CN3raB9atujkEiPpxYAdlgQ_15 = addInt(gBG_dgmeknpHWrtwqMJGQAp9atA, ((NI) 60));
		gBG_dgmeknpHWrtwqMJGQAp9atA = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_15);
	}
	LA3_: ;
	nimln_(553, "terminal.nim");
	T5_ = (NimStringDesc*)0;
	T6_ = (NimStringDesc*)0;
	T6_ = nimIntToStr(gBG_dgmeknpHWrtwqMJGQAp9atA);
	T5_ = rawNewString(T6_->Sup.len + 3);
appendString(T5_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
appendString(T5_, T6_);
appendChar(T5_, 109);
	write_c4mGyJBvK73pdM22jiweKQ(f, T5_);
	popFrame();
}

N_NIMCALL(NIM_BOOL, isatty_POoHvosCWg3Yl5ieYeLHrg)(FILE* f) {
	NIM_BOOL result;
	int T1_;
	int T2_;
	nimfr_("isatty", "terminal.nim")
	result = (NIM_BOOL)0;
	nimln_(564, "terminal.nim");
	nimln_(364, "system.nim");
	nimln_(564, "terminal.nim");
	T1_ = (int)0;
	T1_ = getFileHandle_bZ9c2yojtXoDTUpfyl8h8Rg(f);
	T2_ = (int)0;
	T2_ = isatty(T1_);
	result = !((T2_ == ((NI32) 0)));
	popFrame();
	return result;
}

N_NIMCALL(NIM_CHAR, getch_PZUNldkwV2VhZMU6UCrZTA)(void) {
	NIM_CHAR result;
	int fd;
	struct termios oldMode;
	int T1_;
	int T2_;
	nimfr_("getch", "terminal.nim")
	result = (NIM_CHAR)0;
	nimln_(639, "terminal.nim");
	fd = getFileHandle_bZ9c2yojtXoDTUpfyl8h8Rg(stdin);
	memset((void*)(&oldMode), 0, sizeof(oldMode));
	nimln_(641, "terminal.nim");
	T1_ = (int)0;
	T1_ = tcgetattr(fd, (&oldMode));
	T1_;
	nimln_(642, "terminal.nim");
	setRaw_bWuPmHcnrBG1QQlDC4s7ug(fd, TCSAFLUSH);
	nimln_(643, "terminal.nim");
	result = readChar_ufPUIQ2Rg4xhWjWigciDOg(stdin);
	nimln_(644, "terminal.nim");
	T2_ = (int)0;
	T2_ = tcsetattr(fd, TCSADRAIN, (&oldMode));
	T2_;
	popFrame();
	return result;
}

N_NOCONV(void, resetAttributes_1y1Orb5p0KBhRdFFLR9bNtg)(void) {
	nimfr_("resetAttributes", "terminal.nim")
	nimln_(669, "terminal.nim");
	resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit000)(void) {
	nimfr_("terminal", "terminal.nim")
	nimln_(453, "terminal.nim");
	gFG_g7w4T3anr20OMlWloNx2tQ = ((NI) 0);
	nimln_(454, "terminal.nim");
	gBG_dgmeknpHWrtwqMJGQAp9atA = ((NI) 0);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit000)(void) {
}

