/* Generated by Nim Compiler v0.17.1 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/p/Nim/lib -o /p/calendars/test/nimcache/stdlib_parsecsv.o /p/calendars/test/nimcache/stdlib_parsecsv.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct CsvError_5MMHYN9cM2d1GsHy5O9agEIQ CsvError_5MMHYN9cM2d1GsHy5O9agEIQ;
typedef struct IOError_9czoZw3pzPyrBmb5zTHY1OQ IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct SystemError_Fjf9b9b2IlzRO2tspHxG3tgg SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct CsvParser_e0KmhL4ItditGQKnCUZMoQ CsvParser_e0KmhL4ItditGQKnCUZMoQ;
typedef struct BaseLexer_B6cGbTPhMsqMovc9cOcIHRw BaseLexer_B6cGbTPhMsqMovc9cOcIHRw;
typedef struct StreamObj_RShkcoDOPnoCVhtpN1hDPQ StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
struct CsvError_5MMHYN9cM2d1GsHy5O9agEIQ {
  IOError_9czoZw3pzPyrBmb5zTHY1OQ Sup;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct IntSet_EZObFrE3NC9bIb3YMkY9crZA {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef NU8 TY_nmiMWKVIe46vacnhAFrQvw_Set[32];
struct BaseLexer_B6cGbTPhMsqMovc9cOcIHRw {
  RootObj Sup;
NI bufpos;
NCSTRING buf;
NI bufLen;
StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
TY_nmiMWKVIe46vacnhAFrQvw_Set refillChars;
};
struct CsvParser_e0KmhL4ItditGQKnCUZMoQ {
  BaseLexer_B6cGbTPhMsqMovc9cOcIHRw Sup;
TY_sM4lkSb7zS6F7OVMvW9cffQ* row;
NimStringDesc* filename;
NIM_CHAR sep;
NIM_CHAR quote;
NIM_CHAR esc;
NIM_BOOL skipWhite;
NI currRow;
TY_sM4lkSb7zS6F7OVMvW9cffQ* headers;
};
typedef NU8 FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct PageDesc_fublkgIY4LG3mT51LU2WHg {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef N_NIMCALL_PTR(void, TY_cnkJEp9bna8U6yi9aVW9cAJ0Q) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY_KjFcmLOhf4VQvVcyLJWXZw) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, TY_jlOYFw9cHausuCbPoWx2iiA) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY_Xzm85qBLb9cf9cu8VOfAr8PQ) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, TY_tjaJtoUzLe1BMUbItlcGhQ) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, TY_b9bsIuILxTLVZHPvJBW187A) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
TY_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
TY_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
TY_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
TY_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
TY_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
TY_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw {
  StreamObj_RShkcoDOPnoCVhtpN1hDPQ Sup;
FILE* f;
};
struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, raiseEInvalidCsv_HcftpwJzOOP1xPgLVh0oUg)(NimStringDesc* filename, NI line, NI col, NimStringDesc* msg) __attribute__((noreturn));
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_TY_VgLrzdOR3HwTOOL2IcFN9cA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(void, error_rSVZOSfuDbBAJ4HGxo0CdQ)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NI pos, NimStringDesc* msg);
N_NIMCALL(NI, getColNumber_9cj186ckGjLqyndkoW7bBdg)(BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_NIMCALL(void, open_dmBuwTCvdiT9cdjydWhbTTg)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace);
N_NIMCALL(void, open_xmgaYJZNnO6QcDtac9bs3Vg)(BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NI bufLen, TY_nmiMWKVIe46vacnhAFrQvw_Set refillChars);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, open_grmoJIpX15R5Xfx6m2M1UA)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc* filename, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace);
N_NIMCALL(FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw*, newFileStream_9argyMqCIlB1KDaxUuYVcmw)(NimStringDesc* filename, FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_NIMCALL(void, parseField_dP4vy9acfqJXAsuKp69aq8eQ)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc** a);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, handleCR_IwUEvMBOLRY9cqyar6XKEaw_2)(BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NI, handleLF_IwUEvMBOLRY9cqyar6XKEaw_3)(BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_NIMCALL(NI, processedRows_B9bl8htcg8N29c8FQEl079aPg)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my);
N_NIMCALL(NIM_BOOL, readRow_9bHdhFE0qEvOrDqjuQBz8Pw)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NI columns);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, close_A55CxARYHkQe359a6AS5GRQparsecsv)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my);
N_NIMCALL(void, close_QbedUCk2XwI9c7bbRzXBY0g)(BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L);
N_NIMCALL(void, readHeaderRow_8SSmlmR2zJJf2vnae2Ozsw)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NI, find_sPsD5Eb3qBZqwDJ6Yy4sNQparsecsv)(TY_sM4lkSb7zS6F7OVMvW9cffQ* a, NimStringDesc* item);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, rowEntry_DUXiDWUGeFGligrVn1xHHQ)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc* entry);
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
TNimType NTI_5MMHYN9cM2d1GsHy5O9agEIQ_;
TNimType NTI_VgLrzdOR3HwTOOL2IcFN9cA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_2, "(", 1);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_3, ", ", 2);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_4, ") Error: ", 9);
static NIM_CONST TY_nmiMWKVIe46vacnhAFrQvw_Set TM_3rBY6NOHI29c34PPPPzLAdQ_5 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_6, "cannot open: ", 13);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_9, " expected", 9);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_15, "\012", 1);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_20, "", 0);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_24, " columns expected, but found ", 29);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_25, " columns", 8);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_29, "len(a) == L seq modified while iterating over it", 48);
static N_NIMCALL(void, Marker_TY_VgLrzdOR3HwTOOL2IcFN9cA)(void* p, NI op) {
	CsvError_5MMHYN9cM2d1GsHy5O9agEIQ* a;
	a = (CsvError_5MMHYN9cM2d1GsHy5O9agEIQ*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.up, op);
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim")
	nimln_(273, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(364, "system.nim");
		nimln_(273, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(274, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(275, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(276, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(364, "system.nim");
		nimln_(276, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(277, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(278, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(279, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(280, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, raiseEInvalidCsv_HcftpwJzOOP1xPgLVh0oUg)(NimStringDesc* filename, NI line, NI col, NimStringDesc* msg) {
	CsvError_5MMHYN9cM2d1GsHy5O9agEIQ* e;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	nimfr_("raiseEInvalidCsv", "parsecsv.nim")
	e = (CsvError_5MMHYN9cM2d1GsHy5O9agEIQ*)0;
	nimln_(74, "parsecsv.nim");
	e = (CsvError_5MMHYN9cM2d1GsHy5O9agEIQ*) newObj((&NTI_VgLrzdOR3HwTOOL2IcFN9cA_), sizeof(CsvError_5MMHYN9cM2d1GsHy5O9agEIQ));
	(*e).Sup.Sup.Sup.Sup.m_type = (&NTI_5MMHYN9cM2d1GsHy5O9agEIQ_);
	nimln_(75, "parsecsv.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr(line);
	T3_ = (NimStringDesc*)0;
	T3_ = nimIntToStr(col);
	T1_ = rawNewString(filename->Sup.len + T2_->Sup.len + T3_->Sup.len + msg->Sup.len + 12);
appendString(T1_, filename);
appendString(T1_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_2));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_3));
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_4));
appendString(T1_, msg);
	asgnRefNoCycle((void**) (&(*e).Sup.Sup.Sup.message), T1_);
	nimln_(76, "parsecsv.nim");
	raiseException((Exception*)e, "CsvError");
	popFrame();
}

N_NIMCALL(void, error_rSVZOSfuDbBAJ4HGxo0CdQ)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NI pos, NimStringDesc* msg) {
	NI T1_;
	nimfr_("error", "parsecsv.nim")
	nimln_(79, "parsecsv.nim");
	T1_ = (NI)0;
	T1_ = getColNumber_9cj186ckGjLqyndkoW7bBdg((&(*my).Sup), pos);
	raiseEInvalidCsv_HcftpwJzOOP1xPgLVh0oUg((*my).filename, (*my).Sup.lineNumber, T1_, msg);
	popFrame();
}

N_NIMCALL(void, open_dmBuwTCvdiT9cdjydWhbTTg)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace) {
	BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	nimfr_("open", "parsecsv.nim")
	nimln_(96, "parsecsv.nim");
	T1_ = (BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &my->Sup;
	open_xmgaYJZNnO6QcDtac9bs3Vg(T1_, input, ((NI) 8192), TM_3rBY6NOHI29c34PPPPzLAdQ_5);
	nimln_(97, "parsecsv.nim");
	unsureAsgnRef((void**) (&(*my).filename), copyString(filename));
	nimln_(98, "parsecsv.nim");
	(*my).sep = separator;
	nimln_(99, "parsecsv.nim");
	(*my).quote = quote;
	nimln_(100, "parsecsv.nim");
	(*my).esc = escape;
	nimln_(101, "parsecsv.nim");
	(*my).skipWhite = skipInitialSpace;
	nimln_(102, "parsecsv.nim");
	unsureAsgnRef((void**) (&(*my).row), (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0));
	nimln_(103, "parsecsv.nim");
	(*my).currRow = ((NI) 0);
	popFrame();
}

N_NIMCALL(void, open_grmoJIpX15R5Xfx6m2M1UA)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc* filename, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace) {
	FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw* s;
	StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T6_;
	nimfr_("open", "parsecsv.nim")
	nimln_(109, "parsecsv.nim");
	s = newFileStream_9argyMqCIlB1KDaxUuYVcmw(filename, ((FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
	nimln_(110, "parsecsv.nim");
	{
		NimStringDesc* T5_;
		if (!(s == NIM_NIL)) goto LA3_;
		T5_ = (NimStringDesc*)0;
		T5_ = rawNewString(filename->Sup.len + 13);
appendString(T5_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_6));
appendString(T5_, filename);
		error_rSVZOSfuDbBAJ4HGxo0CdQ((&(*my)), ((NI) 0), T5_);
	}
	LA3_: ;
	nimln_(111, "parsecsv.nim");
	T6_ = (StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
	T6_ = &s->Sup;
	open_dmBuwTCvdiT9cdjydWhbTTg(my, T6_, filename, separator, quote, escape, skipInitialSpace);
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(void, parseField_dP4vy9acfqJXAsuKp69aq8eQ)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc** a) {
	NI pos;
	NCSTRING buf;
	nimfr_("parseField", "parsecsv.nim")
	nimln_(115, "parsecsv.nim");
	pos = (*my).Sup.bufpos;
	nimln_(116, "parsecsv.nim");
	buf = (*my).Sup.buf;
	nimln_(117, "parsecsv.nim");
	{
		if (!(*my).skipWhite) goto LA3_;
		{
			nimln_(118, "parsecsv.nim");
			while (1) {
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_7;
				if (!(((NU8)(buf[pos])) == ((NU8)(32)) || ((NU8)(buf[pos])) == ((NU8)(9)))) goto LA6;
				TM_3rBY6NOHI29c34PPPPzLAdQ_7 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_7);
			} LA6: ;
		}
	}
	LA3_: ;
	nimln_(119, "parsecsv.nim");
	(*a) = setLengthStr((*a), ((NI) 0));
	nimln_(120, "parsecsv.nim");
	{
		NIM_BOOL T9_;
		NI TM_3rBY6NOHI29c34PPPPzLAdQ_8;
		T9_ = (NIM_BOOL)0;
		T9_ = ((NU8)(buf[pos]) == (NU8)((*my).quote));
		if (!(T9_)) goto LA10_;
		nimln_(364, "system.nim");
		nimln_(120, "parsecsv.nim");
		T9_ = !(((NU8)((*my).quote) == (NU8)(0)));
		LA10_: ;
		if (!T9_) goto LA11_;
		nimln_(121, "parsecsv.nim");
		TM_3rBY6NOHI29c34PPPPzLAdQ_8 = addInt(pos, ((NI) 1));
		pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_8);
		{
			nimln_(122, "parsecsv.nim");
			while (1) {
				NIM_CHAR c;
				nimln_(123, "parsecsv.nim");
				c = buf[pos];
				nimln_(124, "parsecsv.nim");
				{
					NimStringDesc* T19_;
					if (!((NU8)(c) == (NU8)(0))) goto LA17_;
					nimln_(125, "parsecsv.nim");
					(*my).Sup.bufpos = pos;
					nimln_(126, "parsecsv.nim");
					T19_ = (NimStringDesc*)0;
					T19_ = rawNewString(10);
appendChar(T19_, (*my).quote);
appendString(T19_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_9));
					error_rSVZOSfuDbBAJ4HGxo0CdQ((&(*my)), pos, T19_);
					nimln_(127, "parsecsv.nim");
					goto LA13;
				}
				goto LA15_;
				LA17_: ;
				{
					nimln_(128, "parsecsv.nim");
					if (!((NU8)(c) == (NU8)((*my).quote))) goto LA21_;
					nimln_(129, "parsecsv.nim");
					{
						NIM_BOOL T25_;
						NI TM_3rBY6NOHI29c34PPPPzLAdQ_10;
						NI TM_3rBY6NOHI29c34PPPPzLAdQ_11;
						T25_ = (NIM_BOOL)0;
						T25_ = ((NU8)((*my).esc) == (NU8)(0));
						if (!(T25_)) goto LA26_;
						TM_3rBY6NOHI29c34PPPPzLAdQ_10 = addInt(pos, ((NI) 1));
						T25_ = ((NU8)(buf[(NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_10)]) == (NU8)((*my).quote));
						LA26_: ;
						if (!T25_) goto LA27_;
						nimln_(130, "parsecsv.nim");
						(*a) = addChar((*a), (*my).quote);
						nimln_(131, "parsecsv.nim");
						TM_3rBY6NOHI29c34PPPPzLAdQ_11 = addInt(pos, ((NI) 2));
						pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_11);
					}
					goto LA23_;
					LA27_: ;
					{
						NI TM_3rBY6NOHI29c34PPPPzLAdQ_12;
						nimln_(133, "parsecsv.nim");
						TM_3rBY6NOHI29c34PPPPzLAdQ_12 = addInt(pos, ((NI) 1));
						pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_12);
						nimln_(134, "parsecsv.nim");
						goto LA13;
					}
					LA23_: ;
				}
				goto LA15_;
				LA21_: ;
				{
					NI TM_3rBY6NOHI29c34PPPPzLAdQ_13;
					NI TM_3rBY6NOHI29c34PPPPzLAdQ_14;
					nimln_(135, "parsecsv.nim");
					if (!((NU8)(c) == (NU8)((*my).esc))) goto LA31_;
					nimln_(136, "parsecsv.nim");
					TM_3rBY6NOHI29c34PPPPzLAdQ_13 = addInt(pos, ((NI) 1));
					(*a) = addChar((*a), buf[(NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_13)]);
					nimln_(137, "parsecsv.nim");
					TM_3rBY6NOHI29c34PPPPzLAdQ_14 = addInt(pos, ((NI) 2));
					pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_14);
				}
				goto LA15_;
				LA31_: ;
				{
					nimln_(139, "parsecsv.nim");
					switch (((NU8)(c))) {
					case 13:
					{
						BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T35_;
						nimln_(141, "parsecsv.nim");
						T35_ = (BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
						T35_ = &my->Sup;
						pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T35_, pos);
						nimln_(142, "parsecsv.nim");
						buf = (*my).Sup.buf;
						nimln_(143, "parsecsv.nim");
						(*a) = resizeString((*a), 1);
appendString((*a), ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_15));
					}
					break;
					case 10:
					{
						BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T37_;
						nimln_(145, "parsecsv.nim");
						T37_ = (BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
						T37_ = &my->Sup;
						pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T37_, pos);
						nimln_(146, "parsecsv.nim");
						buf = (*my).Sup.buf;
						nimln_(147, "parsecsv.nim");
						(*a) = resizeString((*a), 1);
appendString((*a), ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_15));
					}
					break;
					default:
					{
						NI TM_3rBY6NOHI29c34PPPPzLAdQ_16;
						nimln_(149, "parsecsv.nim");
						(*a) = addChar((*a), c);
						nimln_(150, "parsecsv.nim");
						TM_3rBY6NOHI29c34PPPPzLAdQ_16 = addInt(pos, ((NI) 1));
						pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_16);
					}
					break;
					}
				}
				LA15_: ;
			}
		} LA13: ;
	}
	goto LA7_;
	LA11_: ;
	{
		{
			nimln_(152, "parsecsv.nim");
			while (1) {
				NIM_CHAR c_2;
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_17;
				nimln_(153, "parsecsv.nim");
				c_2 = buf[pos];
				nimln_(154, "parsecsv.nim");
				{
					if (!((NU8)(c_2) == (NU8)((*my).sep))) goto LA44_;
					goto LA40;
				}
				LA44_: ;
				nimln_(155, "parsecsv.nim");
				{
					if (!(((NU8)(c_2)) == ((NU8)(13)) || ((NU8)(c_2)) == ((NU8)(10)) || ((NU8)(c_2)) == ((NU8)(0)))) goto LA48_;
					goto LA40;
				}
				LA48_: ;
				nimln_(156, "parsecsv.nim");
				(*a) = addChar((*a), c_2);
				nimln_(157, "parsecsv.nim");
				TM_3rBY6NOHI29c34PPPPzLAdQ_17 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_17);
			}
		} LA40: ;
	}
	LA7_: ;
	nimln_(158, "parsecsv.nim");
	(*my).Sup.bufpos = pos;
	popFrame();
}

N_NIMCALL(NI, processedRows_B9bl8htcg8N29c8FQEl079aPg)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my) {
	NI result;
	nimfr_("processedRows", "parsecsv.nim")
{	result = (NI)0;
	nimln_(162, "parsecsv.nim");
	result = (*my).currRow;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, readRow_9bHdhFE0qEvOrDqjuQBz8Pw)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NI columns) {
	NIM_BOOL result;
	NI col;
	NI oldpos;
	NI TM_3rBY6NOHI29c34PPPPzLAdQ_26;
	nimfr_("readRow", "parsecsv.nim")
	result = (NIM_BOOL)0;
	nimln_(170, "parsecsv.nim");
	col = ((NI) 0);
	nimln_(171, "parsecsv.nim");
	oldpos = (*my).Sup.bufpos;
	{
		nimln_(172, "parsecsv.nim");
		while (1) {
			NI oldlen;
			NI TM_3rBY6NOHI29c34PPPPzLAdQ_21;
			nimln_(364, "system.nim");
			nimln_(172, "parsecsv.nim");
			if (!!(((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)(0)))) goto LA2;
			nimln_(173, "parsecsv.nim");
			oldlen = ((*my).row ? (*my).row->Sup.len : 0);
			nimln_(174, "parsecsv.nim");
			{
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_18;
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_19;
				NimStringDesc* T7_;
				TM_3rBY6NOHI29c34PPPPzLAdQ_18 = addInt(col, ((NI) 1));
				if (!(oldlen < (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_18))) goto LA5_;
				nimln_(175, "parsecsv.nim");
				TM_3rBY6NOHI29c34PPPPzLAdQ_19 = addInt(col, ((NI) 1));
				(*my).row = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*my).row)->Sup, sizeof(NimStringDesc*), ((NI)chckRange((NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_19), ((NI) 0), ((NI) IL64(9223372036854775807)))));
				if ((NU)(col) >= (NU)((*my).row->Sup.len)) raiseIndexError();
				nimln_(176, "parsecsv.nim");
				T7_ = (NimStringDesc*)0;
				T7_ = (*my).row->data[col]; (*my).row->data[col] = copyStringRC1(((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_20));
				if (T7_) nimGCunrefNoCycle(T7_);
			}
			LA5_: ;
			nimln_(177, "parsecsv.nim");
			if ((NU)(col) >= (NU)((*my).row->Sup.len)) raiseIndexError();
			parseField_dP4vy9acfqJXAsuKp69aq8eQ(my, (&(*my).row->data[col]));
			nimln_(178, "parsecsv.nim");
			TM_3rBY6NOHI29c34PPPPzLAdQ_21 = addInt(col, ((NI) 1));
			col = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_21);
			nimln_(179, "parsecsv.nim");
			{
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_22;
				if (!((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)((*my).sep))) goto LA10_;
				nimln_(180, "parsecsv.nim");
				TM_3rBY6NOHI29c34PPPPzLAdQ_22 = addInt((*my).Sup.bufpos, ((NI) 1));
				(*my).Sup.bufpos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_22);
			}
			goto LA8_;
			LA10_: ;
			{
				nimln_(182, "parsecsv.nim");
				switch (((NU8)((*my).Sup.buf[(*my).Sup.bufpos]))) {
				case 13:
				case 10:
				{
					{
						nimln_(185, "parsecsv.nim");
						while (1) {
							nimln_(186, "parsecsv.nim");
							switch (((NU8)((*my).Sup.buf[(*my).Sup.bufpos]))) {
							case 13:
							{
								BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T17_;
								nimln_(187, "parsecsv.nim");
								T17_ = (BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
								T17_ = &my->Sup;
								(*my).Sup.bufpos = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T17_, (*my).Sup.bufpos);
							}
							break;
							case 10:
							{
								BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T19_;
								nimln_(188, "parsecsv.nim");
								T19_ = (BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
								T19_ = &my->Sup;
								(*my).Sup.bufpos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T19_, (*my).Sup.bufpos);
							}
							break;
							default:
							{
								nimln_(189, "parsecsv.nim");
								goto LA14;
							}
							break;
							}
						}
					} LA14: ;
				}
				break;
				case 0:
				{
				}
				break;
				default:
				{
					NimStringDesc* T23_;
					nimln_(191, "parsecsv.nim");
					T23_ = (NimStringDesc*)0;
					T23_ = rawNewString(10);
appendChar(T23_, (*my).sep);
appendString(T23_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_9));
					error_rSVZOSfuDbBAJ4HGxo0CdQ((&(*my)), (*my).Sup.bufpos, T23_);
				}
				break;
				}
				nimln_(192, "parsecsv.nim");
				goto LA1;
			}
			LA8_: ;
		} LA2: ;
	} LA1: ;
	nimln_(194, "parsecsv.nim");
	(*my).row = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*my).row)->Sup, sizeof(NimStringDesc*), ((NI)chckRange(col, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(195, "parsecsv.nim");
	result = (((NI) 0) < col);
	nimln_(196, "parsecsv.nim");
	{
		NIM_BOOL T26_;
		NIM_BOOL T27_;
		NI TM_3rBY6NOHI29c34PPPPzLAdQ_23;
		NimStringDesc* T32_;
		NimStringDesc* T33_;
		NimStringDesc* T34_;
		T26_ = (NIM_BOOL)0;
		T27_ = (NIM_BOOL)0;
		T27_ = result;
		if (!(T27_)) goto LA28_;
		nimln_(364, "system.nim");
		nimln_(196, "parsecsv.nim");
		T27_ = !((col == columns));
		LA28_: ;
		T26_ = T27_;
		if (!(T26_)) goto LA29_;
		T26_ = (((NI) 0) < columns);
		LA29_: ;
		if (!T26_) goto LA30_;
		nimln_(197, "parsecsv.nim");
		TM_3rBY6NOHI29c34PPPPzLAdQ_23 = addInt(oldpos, ((NI) 1));
		T32_ = (NimStringDesc*)0;
		T33_ = (NimStringDesc*)0;
		T33_ = nimIntToStr(columns);
		nimln_(198, "parsecsv.nim");
		T34_ = (NimStringDesc*)0;
		T34_ = nimIntToStr(col);
		T32_ = rawNewString(T33_->Sup.len + T34_->Sup.len + 37);
appendString(T32_, T33_);
appendString(T32_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_24));
appendString(T32_, T34_);
appendString(T32_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_25));
		error_rSVZOSfuDbBAJ4HGxo0CdQ((&(*my)), (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_23), T32_);
	}
	LA30_: ;
	nimln_(199, "parsecsv.nim");
	TM_3rBY6NOHI29c34PPPPzLAdQ_26 = addInt((*my).currRow, ((NI) 1));
	(*my).currRow = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_26);
	popFrame();
	return result;
}

static N_INLINE(void, close_A55CxARYHkQe359a6AS5GRQparsecsv)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my) {
	BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	nimfr_("close", "parsecsv.nim")
	nimln_(203, "parsecsv.nim");
	T1_ = (BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &my->Sup;
	close_QbedUCk2XwI9c7bbRzXBY0g(T1_);
	popFrame();
}

N_NIMCALL(void, readHeaderRow_8SSmlmR2zJJf2vnae2Ozsw)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my) {
	NIM_BOOL present;
	nimfr_("readHeaderRow", "parsecsv.nim")
	nimln_(208, "parsecsv.nim");
	present = readRow_9bHdhFE0qEvOrDqjuQBz8Pw(my, ((NI) 0));
	nimln_(209, "parsecsv.nim");
	{
		if (!present) goto LA3_;
		nimln_(210, "parsecsv.nim");
		genericSeqAssign((&(*my).headers), (*my).row, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, find_sPsD5Eb3qBZqwDJ6Yy4sNQparsecsv)(TY_sM4lkSb7zS6F7OVMvW9cffQ* a, NimStringDesc* item) {
	NI result;
	nimfr_("find", "system.nim")
{	result = (NI)0;
	{
		NimStringDesc* i;
		NI i_2;
		NI L;
		i = (NimStringDesc*)0;
		nimln_(3626, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3627, "system.nim");
		L = (a ? a->Sup.len : 0);
		{
			nimln_(3628, "system.nim");
			while (1) {
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_27;
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_28;
				if (!(i_2 < L)) goto LA3;
				nimln_(3629, "system.nim");
				if ((NU)(i_2) >= (NU)(a->Sup.len)) raiseIndexError();
				i = a->data[i_2];
				nimln_(2300, "system.nim");
				{
					if (!eqStrings(i, item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2301, "system.nim");
				TM_3rBY6NOHI29c34PPPPzLAdQ_27 = addInt(result, ((NI) 1));
				result = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_27);
				nimln_(3630, "system.nim");
				TM_3rBY6NOHI29c34PPPPzLAdQ_28 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_28);
				nimln_(3631, "system.nim");
				{
					if (!!(((a ? a->Sup.len : 0) == L))) goto LA10_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_29));
				}
				LA10_: ;
			} LA3: ;
		}
	}
	nimln_(2302, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, rowEntry_DUXiDWUGeFGligrVn1xHHQ)(CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc* entry) {
	NimStringDesc* result;
	NI index;
	nimfr_("rowEntry", "parsecsv.nim")
	result = (NimStringDesc*)0;
	nimln_(217, "parsecsv.nim");
	index = find_sPsD5Eb3qBZqwDJ6Yy4sNQparsecsv((*my).headers, entry);
	nimln_(218, "parsecsv.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		nimln_(219, "parsecsv.nim");
		if ((NU)(index) >= (NU)((*my).row->Sup.len)) raiseIndexError();
		result = copyString((*my).row->data[index]);
	}
	LA3_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvInit000)(void) {
	nimfr_("parsecsv", "parsecsv.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvDatInit000)(void) {
static TNimNode TM_3rBY6NOHI29c34PPPPzLAdQ_0[1];
NTI_5MMHYN9cM2d1GsHy5O9agEIQ_.size = sizeof(CsvError_5MMHYN9cM2d1GsHy5O9agEIQ);
NTI_5MMHYN9cM2d1GsHy5O9agEIQ_.kind = 17;
NTI_5MMHYN9cM2d1GsHy5O9agEIQ_.base = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[0].len = 0; TM_3rBY6NOHI29c34PPPPzLAdQ_0[0].kind = 2;
NTI_5MMHYN9cM2d1GsHy5O9agEIQ_.node = &TM_3rBY6NOHI29c34PPPPzLAdQ_0[0];
NTI_VgLrzdOR3HwTOOL2IcFN9cA_.size = sizeof(CsvError_5MMHYN9cM2d1GsHy5O9agEIQ*);
NTI_VgLrzdOR3HwTOOL2IcFN9cA_.kind = 22;
NTI_VgLrzdOR3HwTOOL2IcFN9cA_.base = (&NTI_5MMHYN9cM2d1GsHy5O9agEIQ_);
NTI_VgLrzdOR3HwTOOL2IcFN9cA_.marker = Marker_TY_VgLrzdOR3HwTOOL2IcFN9cA;
}

