/* Generated by Nim Compiler v0.17.1 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/p/Nim/lib -o /p/calendars/test/nimcache/stdlib_ospaths.o /p/calendars/test/nimcache/stdlib_ospaths.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY_UV3llMMYFckfui8YMBuUZA TY_UV3llMMYFckfui8YMBuUZA;
typedef struct TY_7q7q3E6Oj24ZNVJb9aonhAg TY_7q7q3E6Oj24ZNVJb9aonhAg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct TY_7q7q3E6Oj24ZNVJb9aonhAg {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, nosjoinPathOpenArray)(NimStringDesc** parts, NI partsLen_0);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(void, nossplitPath)(NimStringDesc* path, TY_UV3llMMYFckfui8YMBuUZA* Result);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NI, parentDirPos_GvT9b2csQmLzVANEJ9bdAuNA)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, nosparentDir)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, nostailDir)(NimStringDesc* path);
N_NIMCALL(NIM_BOOL, nosisRootDir)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, slashdotdotslash__lXoMhn1ZYc9cAJa9bfA61msg_2)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NimStringDesc*, normExt_3yxSdoh5oykvpUqYYeaz2g)(NimStringDesc* ext);
N_NIMCALL(NI, searchExtPos_GvT9b2csQmLzVANEJ9bdAuNA_2)(NimStringDesc* path);
N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY_7q7q3E6Oj24ZNVJb9aonhAg* Result);
N_NIMCALL(NimStringDesc*, nosextractFilename)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, noschangeFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_NIMCALL(NI, noscmpPaths)(NimStringDesc* pathA, NimStringDesc* pathB);
N_NIMCALL(NI, cmp_xEnKsp9cfvO7Do9cTYXo8eJw)(NimStringDesc* x, NimStringDesc* y);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, nosunixToNativePath)(NimStringDesc* path, NimStringDesc* drive);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_jvWQYw9bcuYhftfPX2ynPeg_8, "", 0);

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	nimfr_("joinPath", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(196, "ospaths.nim");
	{
		if (!((head ? head->Sup.len : 0) == ((NI) 0))) goto LA3_;
		nimln_(197, "ospaths.nim");
		result = copyString(tail);
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_2;
		nimln_(198, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_2 = subInt((head ? head->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_2)) > (NU)(head->Sup.len)) raiseIndexError();
		if (!(((NU8)(head->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_2)])) == ((NU8)(47)) || ((NU8)(head->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_2)])) == ((NU8)(47)))) goto LA6_;
		nimln_(199, "ospaths.nim");
		{
			NimStringDesc* T12_;
			NimStringDesc* T13_;
			if ((NU)(((NI) 0)) > (NU)(tail->Sup.len)) raiseIndexError();
			if (!(((NU8)(tail->data[((NI) 0)])) == ((NU8)(47)) || ((NU8)(tail->data[((NI) 0)])) == ((NU8)(47)))) goto LA10_;
			nimln_(200, "ospaths.nim");
			T12_ = (NimStringDesc*)0;
			T13_ = (NimStringDesc*)0;
			T13_ = copyStr(tail, ((NI) 1));
			T12_ = rawNewString(head->Sup.len + T13_->Sup.len + 0);
appendString(T12_, head);
appendString(T12_, T13_);
			result = T12_;
		}
		goto LA8_;
		LA10_: ;
		{
			NimStringDesc* T15_;
			nimln_(202, "ospaths.nim");
			T15_ = (NimStringDesc*)0;
			T15_ = rawNewString(head->Sup.len + tail->Sup.len + 0);
appendString(T15_, head);
appendString(T15_, tail);
			result = T15_;
		}
		LA8_: ;
	}
	goto LA1_;
	LA6_: ;
	{
		nimln_(204, "ospaths.nim");
		{
			NimStringDesc* T21_;
			if ((NU)(((NI) 0)) > (NU)(tail->Sup.len)) raiseIndexError();
			if (!(((NU8)(tail->data[((NI) 0)])) == ((NU8)(47)) || ((NU8)(tail->data[((NI) 0)])) == ((NU8)(47)))) goto LA19_;
			nimln_(205, "ospaths.nim");
			T21_ = (NimStringDesc*)0;
			T21_ = rawNewString(head->Sup.len + tail->Sup.len + 0);
appendString(T21_, head);
appendString(T21_, tail);
			result = T21_;
		}
		goto LA17_;
		LA19_: ;
		{
			NimStringDesc* T23_;
			nimln_(207, "ospaths.nim");
			T23_ = (NimStringDesc*)0;
			T23_ = rawNewString(head->Sup.len + tail->Sup.len + 1);
appendString(T23_, head);
appendChar(T23_, 47);
appendString(T23_, tail);
			result = T23_;
		}
		LA17_: ;
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NimStringDesc*, nosjoinPathOpenArray)(NimStringDesc** parts, NI partsLen_0) {
	NimStringDesc* result;
	nimfr_("joinPath", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(214, "ospaths.nim");
	if ((NU)(((NI) 0)) >= (NU)(partsLen_0)) raiseIndexError();
	result = copyString(parts[((NI) 0)]);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(215, "ospaths.nim");
		colontmp_ = (partsLen_0-1);
		nimln_(1974, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1975, "system.nim");
			while (1) {
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_3;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1976, "system.nim");
				i = res;
				nimln_(216, "ospaths.nim");
				if ((NU)(i) >= (NU)(partsLen_0)) raiseIndexError();
				result = nosjoinPath(result, parts[i]);
				nimln_(1977, "system.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_3 = addInt(res, ((NI) 1));
				res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_3);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	nimfr_("/", "ospaths.nim")
{	result = (NimStringDesc*)0;
	nimln_(228, "ospaths.nim");
	result = nosjoinPath(head, tail);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nossplitPath)(NimStringDesc* path, TY_UV3llMMYFckfui8YMBuUZA* Result) {
	NI sepPos;
	nimfr_("splitPath", "ospaths.nim")
	nimln_(243, "ospaths.nim");
	sepPos = ((NI) -1);
	{
		NI i;
		NI colontmp_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_4;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(244, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_4 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		colontmp_ = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_4);
		nimln_(1945, "system.nim");
		res = colontmp_;
		{
			nimln_(1946, "system.nim");
			while (1) {
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_5;
				nimln_(244, "ospaths.nim");
				if (!(((NI) 0) <= res)) goto LA3;
				nimln_(1947, "system.nim");
				i = res;
				nimln_(245, "ospaths.nim");
				{
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					if (!(((NU8)(path->data[i])) == ((NU8)(47)) || ((NU8)(path->data[i])) == ((NU8)(47)))) goto LA6_;
					nimln_(246, "ospaths.nim");
					sepPos = i;
					nimln_(247, "ospaths.nim");
					goto LA1;
				}
				LA6_: ;
				nimln_(1948, "system.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_5 = subInt(res, ((NI) 1));
				res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_5);
			} LA3: ;
		}
	} LA1: ;
	nimln_(248, "ospaths.nim");
	{
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_6;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_7;
		if (!(((NI) 0) <= sepPos)) goto LA10_;
		nimln_(249, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_6 = subInt(sepPos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field0), copyStrLast(path, ((NI) 0), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_6)));
		nimln_(250, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_7 = addInt(sepPos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field1), copyStr(path, (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_7)));
	}
	goto LA8_;
	LA10_: ;
	{
		nimln_(252, "ospaths.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8)));
		nimln_(253, "ospaths.nim");
		unsureAsgnRef((void**) (&(*Result).Field1), copyString(path));
	}
	LA8_: ;
	popFrame();
}

N_NIMCALL(NI, parentDirPos_GvT9b2csQmLzVANEJ9bdAuNA)(NimStringDesc* path) {
	NI result;
	NI q;
	nimfr_("parentDirPos", "ospaths.nim")
{	result = (NI)0;
	nimln_(256, "ospaths.nim");
	q = ((NI) 1);
	nimln_(257, "ospaths.nim");
	{
		NIM_BOOL T3_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_9;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 1) <= (path ? path->Sup.len : 0));
		if (!(T3_)) goto LA4_;
		TM_jvWQYw9bcuYhftfPX2ynPeg_9 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_9)) > (NU)(path->Sup.len)) raiseIndexError();
		T3_ = (((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_9)])) == ((NU8)(47)) || ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_9)])) == ((NU8)(47)));
		LA4_: ;
		if (!T3_) goto LA5_;
		q = ((NI) 2);
	}
	LA5_: ;
	{
		NI i;
		NI colontmp_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_10;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(258, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_10 = subInt((path ? path->Sup.len : 0), q);
		colontmp_ = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_10);
		nimln_(1945, "system.nim");
		res = colontmp_;
		{
			nimln_(1946, "system.nim");
			while (1) {
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_11;
				nimln_(258, "ospaths.nim");
				if (!(((NI) 0) <= res)) goto LA9;
				nimln_(1947, "system.nim");
				i = res;
				nimln_(259, "ospaths.nim");
				{
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					if (!(((NU8)(path->data[i])) == ((NU8)(47)) || ((NU8)(path->data[i])) == ((NU8)(47)))) goto LA12_;
					result = i;
					goto BeforeRet_;
				}
				LA12_: ;
				nimln_(1948, "system.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_11 = subInt(res, ((NI) 1));
				res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_11);
			} LA9: ;
		}
	}
	nimln_(260, "ospaths.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosparentDir)(NimStringDesc* path) {
	NimStringDesc* result;
	NI sepPos;
	nimfr_("parentDir", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(270, "ospaths.nim");
	sepPos = parentDirPos_GvT9b2csQmLzVANEJ9bdAuNA(path);
	nimln_(271, "ospaths.nim");
	{
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_12;
		if (!(((NI) 0) <= sepPos)) goto LA3_;
		nimln_(272, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_12 = subInt(sepPos, ((NI) 1));
		result = copyStrLast(path, ((NI) 0), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_12));
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(274, "ospaths.nim");
		result = copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nostailDir)(NimStringDesc* path) {
	NimStringDesc* result;
	NI q;
	nimfr_("tailDir", "ospaths.nim")
{	result = (NimStringDesc*)0;
	nimln_(283, "ospaths.nim");
	q = ((NI) 1);
	nimln_(284, "ospaths.nim");
	{
		NIM_BOOL T3_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_13;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 1) <= (path ? path->Sup.len : 0));
		if (!(T3_)) goto LA4_;
		TM_jvWQYw9bcuYhftfPX2ynPeg_13 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_13)) > (NU)(path->Sup.len)) raiseIndexError();
		T3_ = (((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_13)])) == ((NU8)(47)) || ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_13)])) == ((NU8)(47)));
		LA4_: ;
		if (!T3_) goto LA5_;
		q = ((NI) 2);
	}
	LA5_: ;
	{
		NI i;
		NI colontmp_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_14;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(285, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_14 = subInt((path ? path->Sup.len : 0), q);
		colontmp_ = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_14);
		nimln_(1974, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1975, "system.nim");
			while (1) {
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_16;
				if (!(res <= colontmp_)) goto LA9;
				nimln_(1976, "system.nim");
				i = res;
				nimln_(286, "ospaths.nim");
				{
					NI TM_jvWQYw9bcuYhftfPX2ynPeg_15;
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					if (!(((NU8)(path->data[i])) == ((NU8)(47)) || ((NU8)(path->data[i])) == ((NU8)(47)))) goto LA12_;
					nimln_(287, "ospaths.nim");
					TM_jvWQYw9bcuYhftfPX2ynPeg_15 = addInt(i, ((NI) 1));
					result = copyStr(path, (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_15));
					goto BeforeRet_;
				}
				LA12_: ;
				nimln_(1977, "system.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_16 = addInt(res, ((NI) 1));
				res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_16);
			} LA9: ;
		}
	}
	nimln_(288, "ospaths.nim");
	result = copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8));
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nosisRootDir)(NimStringDesc* path) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("isRootDir", "ospaths.nim")
	result = (NIM_BOOL)0;
	nimln_(293, "ospaths.nim");
	T1_ = (NI)0;
	T1_ = parentDirPos_GvT9b2csQmLzVANEJ9bdAuNA(path);
	result = (T1_ < ((NI) 0));
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, slashdotdotslash__lXoMhn1ZYc9cAJa9bfA61msg_2)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	NI sepPos;
	nimfr_("/../", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(323, "ospaths.nim");
	sepPos = parentDirPos_GvT9b2csQmLzVANEJ9bdAuNA(head);
	nimln_(324, "ospaths.nim");
	{
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_17;
		NimStringDesc* T5_;
		if (!(((NI) 0) <= sepPos)) goto LA3_;
		nimln_(325, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_17 = subInt(sepPos, ((NI) 1));
		T5_ = (NimStringDesc*)0;
		T5_ = copyStrLast(head, ((NI) 0), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_17));
		result = slash__lXoMhn1ZYc9cAJa9bfA61msg(T5_, tail);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(327, "ospaths.nim");
		result = slash__lXoMhn1ZYc9cAJa9bfA61msg(head, tail);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, normExt_3yxSdoh5oykvpUqYYeaz2g)(NimStringDesc* ext) {
	NimStringDesc* result;
	nimfr_("normExt", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(330, "ospaths.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ((ext) && (ext)->Sup.len == 0);
		if (T3_) goto LA4_;
		if ((NU)(((NI) 0)) > (NU)(ext->Sup.len)) raiseIndexError();
		T3_ = ((NU8)(ext->data[((NI) 0)]) == (NU8)(46));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = copyString(ext);
	}
	goto LA1_;
	LA5_: ;
	{
		NimStringDesc* T8_;
		nimln_(331, "ospaths.nim");
		T8_ = (NimStringDesc*)0;
		T8_ = rawNewString(ext->Sup.len + 1);
appendChar(T8_, 46);
appendString(T8_, ext);
		result = T8_;
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, searchExtPos_GvT9b2csQmLzVANEJ9bdAuNA_2)(NimStringDesc* path) {
	NI result;
	nimfr_("searchExtPos", "ospaths.nim")
	result = (NI)0;
	nimln_(337, "ospaths.nim");
	result = ((NI) -1);
	{
		NI i;
		NI colontmp_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_18;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(338, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_18 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		colontmp_ = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_18);
		nimln_(1945, "system.nim");
		res = colontmp_;
		{
			nimln_(1946, "system.nim");
			while (1) {
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_19;
				nimln_(338, "ospaths.nim");
				if (!(((NI) 1) <= res)) goto LA3;
				nimln_(1947, "system.nim");
				i = res;
				nimln_(339, "ospaths.nim");
				{
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					if (!((NU8)(path->data[i]) == (NU8)(46))) goto LA6_;
					nimln_(340, "ospaths.nim");
					result = i;
					nimln_(341, "ospaths.nim");
					goto LA1;
				}
				goto LA4_;
				LA6_: ;
				{
					nimln_(342, "ospaths.nim");
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					if (!(((NU8)(path->data[i])) == ((NU8)(47)) || ((NU8)(path->data[i])) == ((NU8)(47)))) goto LA9_;
					nimln_(343, "ospaths.nim");
					goto LA1;
				}
				goto LA4_;
				LA9_: ;
				LA4_: ;
				nimln_(1948, "system.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_19 = subInt(res, ((NI) 1));
				res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_19);
			} LA3: ;
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY_7q7q3E6Oj24ZNVJb9aonhAg* Result) {
	nimfr_("splitFile", "ospaths.nim")
	nimln_(362, "ospaths.nim");
	{
		NIM_BOOL T3_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_20;
		T3_ = (NIM_BOOL)0;
		T3_ = ((path ? path->Sup.len : 0) == ((NI) 0));
		if (T3_) goto LA4_;
		TM_jvWQYw9bcuYhftfPX2ynPeg_20 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_20)) > (NU)(path->Sup.len)) raiseIndexError();
		T3_ = (((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_20)])) == ((NU8)(47)) || ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_20)])) == ((NU8)(47)));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(363, "ospaths.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), copyString(path));
		unsureAsgnRef((void**) (&(*Result).Field1), copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8)));
		unsureAsgnRef((void**) (&(*Result).Field2), copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8)));
	}
	goto LA1_;
	LA5_: ;
	{
		NI sepPos;
		NI dotPos;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_24;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_25;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_26;
		nimln_(365, "ospaths.nim");
		sepPos = ((NI) -1);
		nimln_(366, "ospaths.nim");
		dotPos = (path ? path->Sup.len : 0);
		{
			NI i;
			NI colontmp_;
			NI TM_jvWQYw9bcuYhftfPX2ynPeg_21;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(367, "ospaths.nim");
			TM_jvWQYw9bcuYhftfPX2ynPeg_21 = subInt((path ? path->Sup.len : 0), ((NI) 1));
			colontmp_ = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_21);
			nimln_(1945, "system.nim");
			res = colontmp_;
			{
				nimln_(1946, "system.nim");
				while (1) {
					NI TM_jvWQYw9bcuYhftfPX2ynPeg_23;
					nimln_(367, "ospaths.nim");
					if (!(((NI) 0) <= res)) goto LA10;
					nimln_(1947, "system.nim");
					i = res;
					nimln_(368, "ospaths.nim");
					{
						if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
						if (!((NU8)(path->data[i]) == (NU8)(46))) goto LA13_;
						nimln_(369, "ospaths.nim");
						{
							NIM_BOOL T17_;
							NIM_BOOL T18_;
							NI TM_jvWQYw9bcuYhftfPX2ynPeg_22;
							T17_ = (NIM_BOOL)0;
							T18_ = (NIM_BOOL)0;
							T18_ = (dotPos == (path ? path->Sup.len : 0));
							if (!(T18_)) goto LA19_;
							T18_ = (((NI) 0) < i);
							LA19_: ;
							T17_ = T18_;
							if (!(T17_)) goto LA20_;
							nimln_(1156, "system.nim");
							nimln_(370, "ospaths.nim");
							TM_jvWQYw9bcuYhftfPX2ynPeg_22 = subInt(i, ((NI) 1));
							if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_22)) > (NU)(path->Sup.len)) raiseIndexError();
							T17_ = !((((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_22)])) == ((NU8)(47)) || ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_22)])) == ((NU8)(47))));
							LA20_: ;
							if (!T17_) goto LA21_;
							dotPos = i;
						}
						LA21_: ;
					}
					goto LA11_;
					LA13_: ;
					{
						nimln_(371, "ospaths.nim");
						if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
						if (!(((NU8)(path->data[i])) == ((NU8)(47)) || ((NU8)(path->data[i])) == ((NU8)(47)))) goto LA24_;
						nimln_(372, "ospaths.nim");
						sepPos = i;
						nimln_(373, "ospaths.nim");
						goto LA8;
					}
					goto LA11_;
					LA24_: ;
					LA11_: ;
					nimln_(1948, "system.nim");
					TM_jvWQYw9bcuYhftfPX2ynPeg_23 = subInt(res, ((NI) 1));
					res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_23);
				} LA10: ;
			}
		} LA8: ;
		nimln_(374, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_24 = subInt(sepPos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field0), copyStrLast(path, ((NI) 0), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_24)));
		nimln_(375, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_25 = addInt(sepPos, ((NI) 1));
		TM_jvWQYw9bcuYhftfPX2ynPeg_26 = subInt(dotPos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field1), copyStrLast(path, (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_25), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_26)));
		nimln_(376, "ospaths.nim");
		unsureAsgnRef((void**) (&(*Result).Field2), copyStr(path, dotPos));
	}
	LA1_: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, nosextractFilename)(NimStringDesc* path) {
	NimStringDesc* result;
	nimfr_("extractFilename", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(382, "ospaths.nim");
	{
		NIM_BOOL T3_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_27;
		T3_ = (NIM_BOOL)0;
		T3_ = ((path ? path->Sup.len : 0) == ((NI) 0));
		if (T3_) goto LA4_;
		TM_jvWQYw9bcuYhftfPX2ynPeg_27 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_27)) > (NU)(path->Sup.len)) raiseIndexError();
		T3_ = (((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_27)])) == ((NU8)(47)) || ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_27)])) == ((NU8)(47)));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(383, "ospaths.nim");
		result = copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8));
	}
	goto LA1_;
	LA5_: ;
	{
		TY_UV3llMMYFckfui8YMBuUZA T8_;
		nimln_(385, "ospaths.nim");
		memset((void*)(&T8_), 0, sizeof(T8_));
		nossplitPath(path, (&T8_));
		result = copyString(T8_.Field1);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, noschangeFileExt)(NimStringDesc* filename, NimStringDesc* ext) {
	NimStringDesc* result;
	NI extPos;
	nimfr_("changeFileExt", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(397, "ospaths.nim");
	extPos = searchExtPos_GvT9b2csQmLzVANEJ9bdAuNA_2(filename);
	nimln_(398, "ospaths.nim");
	{
		NimStringDesc* T5_;
		NimStringDesc* T6_;
		if (!(extPos < ((NI) 0))) goto LA3_;
		T5_ = (NimStringDesc*)0;
		T6_ = (NimStringDesc*)0;
		T6_ = normExt_3yxSdoh5oykvpUqYYeaz2g(ext);
		T5_ = rawNewString(filename->Sup.len + T6_->Sup.len + 0);
appendString(T5_, filename);
appendString(T5_, T6_);
		result = T5_;
	}
	goto LA1_;
	LA3_: ;
	{
		NimStringDesc* T8_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_28;
		NimStringDesc* T9_;
		NimStringDesc* T10_;
		nimln_(399, "ospaths.nim");
		T8_ = (NimStringDesc*)0;
		TM_jvWQYw9bcuYhftfPX2ynPeg_28 = subInt(extPos, ((NI) 1));
		T9_ = (NimStringDesc*)0;
		T9_ = copyStrLast(filename, ((NI) 0), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_28));
		T10_ = (NimStringDesc*)0;
		T10_ = normExt_3yxSdoh5oykvpUqYYeaz2g(ext);
		T8_ = rawNewString(T9_->Sup.len + T10_->Sup.len + 0);
appendString(T8_, T9_);
appendString(T8_, T10_);
		result = T8_;
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext) {
	NimStringDesc* result;
	NI extPos;
	nimfr_("addFileExt", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(409, "ospaths.nim");
	extPos = searchExtPos_GvT9b2csQmLzVANEJ9bdAuNA_2(filename);
	nimln_(410, "ospaths.nim");
	{
		NimStringDesc* T5_;
		NimStringDesc* T6_;
		if (!(extPos < ((NI) 0))) goto LA3_;
		T5_ = (NimStringDesc*)0;
		T6_ = (NimStringDesc*)0;
		T6_ = normExt_3yxSdoh5oykvpUqYYeaz2g(ext);
		T5_ = rawNewString(filename->Sup.len + T6_->Sup.len + 0);
appendString(T5_, filename);
appendString(T5_, T6_);
		result = T5_;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(411, "ospaths.nim");
		result = copyString(filename);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, noscmpPaths)(NimStringDesc* pathA, NimStringDesc* pathB) {
	NI result;
	nimfr_("cmpPaths", "ospaths.nim")
	result = (NI)0;
	nimln_(423, "ospaths.nim");
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(424, "ospaths.nim");
		result = cmp_xEnKsp9cfvO7Do9cTYXo8eJw(pathA, pathB);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(430, "ospaths.nim");
		result = nsuCmpIgnoreCase(pathA, pathB);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringDesc* path) {
	NIM_BOOL result;
	nimfr_("isAbsolute", "ospaths.nim")
	result = (NIM_BOOL)0;
	nimln_(445, "ospaths.nim");
	if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
	result = ((NU8)(path->data[((NI) 0)]) == (NU8)(47));
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosunixToNativePath)(NimStringDesc* path, NimStringDesc* drive) {
	NimStringDesc* result;
	nimfr_("unixToNativePath", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(460, "ospaths.nim");
	result = copyString(path);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void) {
	nimfr_("ospaths", "ospaths.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void) {
}

